all: false
template: testify
packages:
  thoreinstein.com/rig/pkg/knowledge:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      PluginManager: {}
  thoreinstein.com/rig/pkg/api/v1:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      KnowledgeServiceClient: {}
