package sdk

import (
	"context"
	"net"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	apiv1 "thoreinstein.com/rig/pkg/api/v1"
)

// stubSecretServer is a minimal SecretService for testing SDK client behavior.
type stubSecretServer struct {
	apiv1.UnimplementedSecretServiceServer

	// getSecretFunc, if set, handles GetSecret RPCs.
	getSecretFunc func(ctx context.Context, req *apiv1.GetSecretRequest) (*apiv1.GetSecretResponse, error)

	// getSecretsFunc, if set, handles GetSecrets RPCs.
	getSecretsFunc func(ctx context.Context, req *apiv1.GetSecretsRequest) (*apiv1.GetSecretsResponse, error)

	// refreshTokenFunc, if set, handles RefreshToken RPCs.
	refreshTokenFunc func(ctx context.Context, req *apiv1.RefreshTokenRequest) (*apiv1.RefreshTokenResponse, error)
}

func (s *stubSecretServer) GetSecret(ctx context.Context, req *apiv1.GetSecretRequest) (*apiv1.GetSecretResponse, error) {
	if s.getSecretFunc != nil {
		return s.getSecretFunc(ctx, req)
	}
	return nil, status.Errorf(codes.Unimplemented, "not configured")
}

func (s *stubSecretServer) GetSecrets(ctx context.Context, req *apiv1.GetSecretsRequest) (*apiv1.GetSecretsResponse, error) {
	if s.getSecretsFunc != nil {
		return s.getSecretsFunc(ctx, req)
	}
	return nil, status.Errorf(codes.Unimplemented, "not configured")
}

func (s *stubSecretServer) RefreshToken(ctx context.Context, req *apiv1.RefreshTokenRequest) (*apiv1.RefreshTokenResponse, error) {
	if s.refreshTokenFunc != nil {
		return s.refreshTokenFunc(ctx, req)
	}
	return nil, status.Errorf(codes.Unimplemented, "not configured")
}

// startStubServer starts a gRPC server on a temp UDS and returns the socket path.
// The server is stopped when the test completes.
func startStubServer(t *testing.T, stub *stubSecretServer) string {
	t.Helper()

	// Use /tmp directly to avoid the long paths generated by t.TempDir() on Darwin.
	dir, err := os.MkdirTemp("/tmp", "rig-t-") //nolint:usetesting // t.TempDir() is too long for Darwin UDS
	require.NoError(t, err)
	t.Cleanup(func() { _ = os.RemoveAll(dir) })

	sockPath := filepath.Join(dir, "s.sock")
	lis, err := net.Listen("unix", sockPath)
	require.NoError(t, err)

	srv := grpc.NewServer()
	apiv1.RegisterSecretServiceServer(srv, stub)

	go func() { _ = srv.Serve(lis) }()
	t.Cleanup(srv.GracefulStop)

	return sockPath
}

func TestSecret_GetSecret_with_SecretValue(t *testing.T) {
	stub := &stubSecretServer{
		getSecretFunc: func(_ context.Context, req *apiv1.GetSecretRequest) (*apiv1.GetSecretResponse, error) {
			if req.Token != "tok-1" {
				return nil, status.Errorf(codes.Unauthenticated, "bad token")
			}
			return &apiv1.GetSecretResponse{
				Secret: &apiv1.SecretValue{Value: "modern-value"},
			}, nil
		},
	}
	sock := startStubServer(t, stub)

	s := NewSecret(WithSecretHostEndpoint(sock), WithSecretToken("tok-1"))
	defer s.Close()

	val, err := s.GetSecret(t.Context(), "my-key")
	require.NoError(t, err)
	require.Equal(t, "modern-value", val)
}

func TestSecret_GetSecret_legacy_fallback(t *testing.T) {
	stub := &stubSecretServer{
		getSecretFunc: func(_ context.Context, _ *apiv1.GetSecretRequest) (*apiv1.GetSecretResponse, error) {
			// Simulate a legacy host that only sets the deprecated Value field.
			return &apiv1.GetSecretResponse{
				Value: "legacy-value",
			}, nil
		},
	}
	sock := startStubServer(t, stub)

	s := NewSecret(WithSecretHostEndpoint(sock), WithSecretToken("tok-1"))
	defer s.Close()

	val, err := s.GetSecret(t.Context(), "key")
	require.NoError(t, err)
	require.Equal(t, "legacy-value", val)
}

func TestSecret_GetSecret_legacy_empty_string(t *testing.T) {
	stub := &stubSecretServer{
		getSecretFunc: func(_ context.Context, _ *apiv1.GetSecretRequest) (*apiv1.GetSecretResponse, error) {
			// Legacy host returning an empty string value (valid secret).
			return &apiv1.GetSecretResponse{
				Value: "",
			}, nil
		},
	}
	sock := startStubServer(t, stub)

	s := NewSecret(WithSecretHostEndpoint(sock), WithSecretToken("tok-1"))
	defer s.Close()

	val, err := s.GetSecret(t.Context(), "key")
	require.NoError(t, err)
	require.Equal(t, "", val, "empty string is a valid secret from legacy hosts")
}

func TestSecret_GetSecrets(t *testing.T) {
	tests := []struct {
		name       string
		keys       []string
		serverResp *apiv1.GetSecretsResponse
		want       map[string]string
	}{
		{
			name: "all_keys_found",
			keys: []string{"a", "b"},
			serverResp: &apiv1.GetSecretsResponse{
				Secrets: map[string]*apiv1.SecretValue{
					"a": {Value: "val-a"},
					"b": {Value: "val-b"},
				},
			},
			want: map[string]string{"a": "val-a", "b": "val-b"},
		},
		{
			name: "partial_keys_omitted",
			keys: []string{"a", "missing"},
			serverResp: &apiv1.GetSecretsResponse{
				Secrets: map[string]*apiv1.SecretValue{
					"a": {Value: "val-a"},
				},
			},
			want: map[string]string{"a": "val-a"},
		},
		{
			name: "nil_value_in_map_returns_empty_string",
			keys: []string{"a"},
			serverResp: &apiv1.GetSecretsResponse{
				Secrets: map[string]*apiv1.SecretValue{
					"a": nil,
				},
			},
			// Proto3 deserializes nil map values as empty messages, so the
			// client sees a non-nil *SecretValue with Value="".
			want: map[string]string{"a": ""},
		},
		{
			name: "empty_response",
			keys: []string{"a"},
			serverResp: &apiv1.GetSecretsResponse{
				Secrets: map[string]*apiv1.SecretValue{},
			},
			want: map[string]string{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			stub := &stubSecretServer{
				getSecretsFunc: func(_ context.Context, _ *apiv1.GetSecretsRequest) (*apiv1.GetSecretsResponse, error) {
					return tt.serverResp, nil
				},
			}
			sock := startStubServer(t, stub)

			s := NewSecret(WithSecretHostEndpoint(sock), WithSecretToken("tok"))
			defer s.Close()

			got, err := s.GetSecrets(t.Context(), tt.keys)
			require.NoError(t, err)
			require.Equal(t, tt.want, got)
		})
	}
}

func TestSecret_RefreshToken_updates_stored_token(t *testing.T) {
	stub := &stubSecretServer{
		refreshTokenFunc: func(_ context.Context, req *apiv1.RefreshTokenRequest) (*apiv1.RefreshTokenResponse, error) {
			if req.CurrentToken != "old-token" {
				return nil, status.Errorf(codes.Unauthenticated, "bad token")
			}
			return &apiv1.RefreshTokenResponse{NewToken: "new-token"}, nil
		},
	}
	sock := startStubServer(t, stub)

	s := NewSecret(WithSecretHostEndpoint(sock), WithSecretToken("old-token"))
	defer s.Close()

	newTok, err := s.RefreshToken(t.Context())
	require.NoError(t, err)
	require.Equal(t, "new-token", newTok)

	// Verify the internal token was updated.
	s.mu.Lock()
	storedToken := s.token
	s.mu.Unlock()
	require.Equal(t, "new-token", storedToken)
}

func TestSecret_RefreshToken_concurrent_no_overwrite(t *testing.T) {
	// Simulate a scenario where another goroutine rotates the token while our
	// RPC is in flight. The compare-and-swap should preserve the newer token.
	var s *Secret
	stub := &stubSecretServer{
		refreshTokenFunc: func(_ context.Context, _ *apiv1.RefreshTokenRequest) (*apiv1.RefreshTokenResponse, error) {
			// While the RPC is in flight, simulate another goroutine rotating the token.
			s.mu.Lock()
			s.token = "already-rotated"
			s.mu.Unlock()
			return &apiv1.RefreshTokenResponse{NewToken: "stale-new-token"}, nil
		},
	}
	sock := startStubServer(t, stub)

	s = NewSecret(WithSecretHostEndpoint(sock), WithSecretToken("original"))
	defer s.Close()

	newTok, err := s.RefreshToken(t.Context())
	require.NoError(t, err)
	require.Equal(t, "stale-new-token", newTok, "return value should be the RPC response")

	// The stored token should NOT have been overwritten because compare-and-swap
	// detects that s.token ("already-rotated") != currentToken ("original").
	s.mu.Lock()
	storedToken := s.token
	s.mu.Unlock()
	require.Equal(t, "already-rotated", storedToken, "compare-and-swap should preserve newer token")
}

func TestSecret_GetSecret_unauthenticated_error(t *testing.T) {
	stub := &stubSecretServer{
		getSecretFunc: func(_ context.Context, _ *apiv1.GetSecretRequest) (*apiv1.GetSecretResponse, error) {
			return nil, status.Errorf(codes.Unauthenticated, "invalid token")
		},
	}
	sock := startStubServer(t, stub)

	s := NewSecret(WithSecretHostEndpoint(sock), WithSecretToken("bad"))
	defer s.Close()

	_, err := s.GetSecret(t.Context(), "key")
	require.Error(t, err)

	st, ok := status.FromError(err)
	require.True(t, ok, "error should be a gRPC status")
	require.Equal(t, codes.Unauthenticated, st.Code())
}
