// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/assistant.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents a single message in a conversation.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role is the sender's role: "user", "assistant", or "system".
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// content is the text of the message.
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatRequest is the input for Chat.
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// messages is the conversation history.
	Messages      []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ChatResponse is the final result of a non-streaming Chat call.
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content is the generated text.
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// stop_reason indicates why the generation stopped (e.g., "end_turn").
	StopReason string `protobuf:"bytes,2,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	// input_tokens is the number of tokens in the prompt.
	InputTokens int32 `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	// output_tokens is the number of tokens in the response.
	OutputTokens  int32 `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *ChatResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *ChatResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

// StreamChatRequest is the input for StreamChat.
type StreamChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// messages is the conversation history.
	Messages      []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatRequest) Reset() {
	*x = StreamChatRequest{}
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatRequest) ProtoMessage() {}

func (x *StreamChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatRequest.ProtoReflect.Descriptor instead.
func (*StreamChatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *StreamChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// StreamChatResponse is a fragment of a streaming response.
type StreamChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content is the fragment of text generated in this chunk.
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// done is true if this is the final chunk of the stream.
	Done          bool `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatResponse) Reset() {
	*x = StreamChatResponse{}
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatResponse) ProtoMessage() {}

func (x *StreamChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatResponse.ProtoReflect.Descriptor instead.
func (*StreamChatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_assistant_proto_rawDescGZIP(), []int{4}
}

func (x *StreamChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamChatResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_pkg_api_v1_assistant_proto protoreflect.FileDescriptor

const file_pkg_api_v1_assistant_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/api/v1/assistant.proto\x12\x06rig.v1\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\":\n" +
	"\vChatRequest\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.rig.v1.MessageR\bmessages\"\x91\x01\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vstop_reason\x18\x02 \x01(\tR\n" +
	"stopReason\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\"@\n" +
	"\x11StreamChatRequest\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.rig.v1.MessageR\bmessages\"B\n" +
	"\x12StreamChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done2\x8c\x01\n" +
	"\x10AssistantService\x121\n" +
	"\x04Chat\x12\x13.rig.v1.ChatRequest\x1a\x14.rig.v1.ChatResponse\x12E\n" +
	"\n" +
	"StreamChat\x12\x19.rig.v1.StreamChatRequest\x1a\x1a.rig.v1.StreamChatResponse0\x01B'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_assistant_proto_rawDescOnce sync.Once
	file_pkg_api_v1_assistant_proto_rawDescData []byte
)

func file_pkg_api_v1_assistant_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_assistant_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_assistant_proto_rawDesc), len(file_pkg_api_v1_assistant_proto_rawDesc)))
	})
	return file_pkg_api_v1_assistant_proto_rawDescData
}

var file_pkg_api_v1_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_v1_assistant_proto_goTypes = []any{
	(*Message)(nil),            // 0: rig.v1.Message
	(*ChatRequest)(nil),        // 1: rig.v1.ChatRequest
	(*ChatResponse)(nil),       // 2: rig.v1.ChatResponse
	(*StreamChatRequest)(nil),  // 3: rig.v1.StreamChatRequest
	(*StreamChatResponse)(nil), // 4: rig.v1.StreamChatResponse
}
var file_pkg_api_v1_assistant_proto_depIdxs = []int32{
	0, // 0: rig.v1.ChatRequest.messages:type_name -> rig.v1.Message
	0, // 1: rig.v1.StreamChatRequest.messages:type_name -> rig.v1.Message
	1, // 2: rig.v1.AssistantService.Chat:input_type -> rig.v1.ChatRequest
	3, // 3: rig.v1.AssistantService.StreamChat:input_type -> rig.v1.StreamChatRequest
	2, // 4: rig.v1.AssistantService.Chat:output_type -> rig.v1.ChatResponse
	4, // 5: rig.v1.AssistantService.StreamChat:output_type -> rig.v1.StreamChatResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_assistant_proto_init() }
func file_pkg_api_v1_assistant_proto_init() {
	if File_pkg_api_v1_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_assistant_proto_rawDesc), len(file_pkg_api_v1_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_assistant_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_assistant_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_assistant_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_assistant_proto = out.File
	file_pkg_api_v1_assistant_proto_goTypes = nil
	file_pkg_api_v1_assistant_proto_depIdxs = nil
}
