// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/context.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in pkg/api/v1/context.proto.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Deprecated: token-based auth is replaced by connection-bound identity.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_pkg_api_v1_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_context_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in pkg/api/v1/context.proto.
func (x *GetContextRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectRoot   string                 `protobuf:"bytes,1,opt,name=project_root,json=projectRoot,proto3" json:"project_root,omitempty"`
	WorktreeRoot  string                 `protobuf:"bytes,2,opt,name=worktree_root,json=worktreeRoot,proto3" json:"worktree_root,omitempty"`
	TicketId      string                 `protobuf:"bytes,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_pkg_api_v1_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_context_proto_rawDescGZIP(), []int{1}
}

func (x *GetContextResponse) GetProjectRoot() string {
	if x != nil {
		return x.ProjectRoot
	}
	return ""
}

func (x *GetContextResponse) GetWorktreeRoot() string {
	if x != nil {
		return x.WorktreeRoot
	}
	return ""
}

func (x *GetContextResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *GetContextResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_api_v1_context_proto protoreflect.FileDescriptor

const file_pkg_api_v1_context_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/api/v1/context.proto\x12\x06rig.v1\x1a\x1cgoogle/protobuf/struct.proto\"-\n" +
	"\x11GetContextRequest\x12\x18\n" +
	"\x05token\x18\x01 \x01(\tB\x02\x18\x01R\x05token\"\xae\x01\n" +
	"\x12GetContextResponse\x12!\n" +
	"\fproject_root\x18\x01 \x01(\tR\vprojectRoot\x12#\n" +
	"\rworktree_root\x18\x02 \x01(\tR\fworktreeRoot\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\tR\bticketId\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata2U\n" +
	"\x0eContextService\x12C\n" +
	"\n" +
	"GetContext\x12\x19.rig.v1.GetContextRequest\x1a\x1a.rig.v1.GetContextResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_context_proto_rawDescOnce sync.Once
	file_pkg_api_v1_context_proto_rawDescData []byte
)

func file_pkg_api_v1_context_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_context_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_context_proto_rawDesc), len(file_pkg_api_v1_context_proto_rawDesc)))
	})
	return file_pkg_api_v1_context_proto_rawDescData
}

var file_pkg_api_v1_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_v1_context_proto_goTypes = []any{
	(*GetContextRequest)(nil),  // 0: rig.v1.GetContextRequest
	(*GetContextResponse)(nil), // 1: rig.v1.GetContextResponse
	(*structpb.Struct)(nil),    // 2: google.protobuf.Struct
}
var file_pkg_api_v1_context_proto_depIdxs = []int32{
	2, // 0: rig.v1.GetContextResponse.metadata:type_name -> google.protobuf.Struct
	0, // 1: rig.v1.ContextService.GetContext:input_type -> rig.v1.GetContextRequest
	1, // 2: rig.v1.ContextService.GetContext:output_type -> rig.v1.GetContextResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_context_proto_init() }
func file_pkg_api_v1_context_proto_init() {
	if File_pkg_api_v1_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_context_proto_rawDesc), len(file_pkg_api_v1_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_context_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_context_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_context_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_context_proto = out.File
	file_pkg_api_v1_context_proto_goTypes = nil
	file_pkg_api_v1_context_proto_depIdxs = nil
}
