// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/api/v1/daemon.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_Execute_FullMethodName  = "/rig.v1.DaemonService/Execute"
	DaemonService_Status_FullMethodName   = "/rig.v1.DaemonService/Status"
	DaemonService_Shutdown_FullMethodName = "/rig.v1.DaemonService/Shutdown"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService provides an interface for the Rig CLI to interact with a
// background daemon managing plugin processes.
type DaemonServiceClient interface {
	// Execute starts a command execution session. It uses a bi-directional stream
	// to multiplex command output and UI interactions.
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse], error)
	// Status returns the current state of the daemon and its managed plugins.
	Status(ctx context.Context, in *DaemonServiceStatusRequest, opts ...grpc.CallOption) (*DaemonServiceStatusResponse, error)
	// Shutdown requests a graceful termination of the daemon.
	Shutdown(ctx context.Context, in *DaemonServiceShutdownRequest, opts ...grpc.CallOption) (*DaemonServiceShutdownResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_ExecuteClient = grpc.BidiStreamingClient[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse]

func (c *daemonServiceClient) Status(ctx context.Context, in *DaemonServiceStatusRequest, opts ...grpc.CallOption) (*DaemonServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonServiceStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Shutdown(ctx context.Context, in *DaemonServiceShutdownRequest, opts ...grpc.CallOption) (*DaemonServiceShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonServiceShutdownResponse)
	err := c.cc.Invoke(ctx, DaemonService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService provides an interface for the Rig CLI to interact with a
// background daemon managing plugin processes.
type DaemonServiceServer interface {
	// Execute starts a command execution session. It uses a bi-directional stream
	// to multiplex command output and UI interactions.
	Execute(grpc.BidiStreamingServer[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse]) error
	// Status returns the current state of the daemon and its managed plugins.
	Status(context.Context, *DaemonServiceStatusRequest) (*DaemonServiceStatusResponse, error)
	// Shutdown requests a graceful termination of the daemon.
	Shutdown(context.Context, *DaemonServiceShutdownRequest) (*DaemonServiceShutdownResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) Execute(grpc.BidiStreamingServer[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedDaemonServiceServer) Status(context.Context, *DaemonServiceStatusRequest) (*DaemonServiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDaemonServiceServer) Shutdown(context.Context, *DaemonServiceShutdownRequest) (*DaemonServiceShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonServiceServer).Execute(&grpc.GenericServerStream[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_ExecuteServer = grpc.BidiStreamingServer[DaemonServiceExecuteRequest, DaemonServiceExecuteResponse]

func _DaemonService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Status(ctx, req.(*DaemonServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonServiceShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Shutdown(ctx, req.(*DaemonServiceShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rig.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _DaemonService_Status_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DaemonService_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _DaemonService_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/v1/daemon.proto",
}
