// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/daemon.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DaemonServiceExecuteRequest is sent from the CLI to the Daemon.
type DaemonServiceExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DaemonServiceExecuteRequest_Command
	//	*DaemonServiceExecuteRequest_UiResponse
	Payload       isDaemonServiceExecuteRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonServiceExecuteRequest) Reset() {
	*x = DaemonServiceExecuteRequest{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonServiceExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonServiceExecuteRequest) ProtoMessage() {}

func (x *DaemonServiceExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonServiceExecuteRequest.ProtoReflect.Descriptor instead.
func (*DaemonServiceExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonServiceExecuteRequest) GetPayload() isDaemonServiceExecuteRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DaemonServiceExecuteRequest) GetCommand() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*DaemonServiceExecuteRequest_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *DaemonServiceExecuteRequest) GetUiResponse() *InteractRequest {
	if x != nil {
		if x, ok := x.Payload.(*DaemonServiceExecuteRequest_UiResponse); ok {
			return x.UiResponse
		}
	}
	return nil
}

type isDaemonServiceExecuteRequest_Payload interface {
	isDaemonServiceExecuteRequest_Payload()
}

type DaemonServiceExecuteRequest_Command struct {
	Command *CommandRequest `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type DaemonServiceExecuteRequest_UiResponse struct {
	UiResponse *InteractRequest `protobuf:"bytes,2,opt,name=ui_response,json=uiResponse,proto3,oneof"` // Response to a UI request (InteractResponse)
}

func (*DaemonServiceExecuteRequest_Command) isDaemonServiceExecuteRequest_Payload() {}

func (*DaemonServiceExecuteRequest_UiResponse) isDaemonServiceExecuteRequest_Payload() {}

// DaemonServiceExecuteResponse is sent from the Daemon to the CLI.
type DaemonServiceExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DaemonServiceExecuteResponse_Output
	//	*DaemonServiceExecuteResponse_UiRequest
	//	*DaemonServiceExecuteResponse_Error
	Payload       isDaemonServiceExecuteResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonServiceExecuteResponse) Reset() {
	*x = DaemonServiceExecuteResponse{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonServiceExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonServiceExecuteResponse) ProtoMessage() {}

func (x *DaemonServiceExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonServiceExecuteResponse.ProtoReflect.Descriptor instead.
func (*DaemonServiceExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *DaemonServiceExecuteResponse) GetPayload() isDaemonServiceExecuteResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DaemonServiceExecuteResponse) GetOutput() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Payload.(*DaemonServiceExecuteResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *DaemonServiceExecuteResponse) GetUiRequest() *InteractResponse {
	if x != nil {
		if x, ok := x.Payload.(*DaemonServiceExecuteResponse_UiRequest); ok {
			return x.UiRequest
		}
	}
	return nil
}

func (x *DaemonServiceExecuteResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*DaemonServiceExecuteResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isDaemonServiceExecuteResponse_Payload interface {
	isDaemonServiceExecuteResponse_Payload()
}

type DaemonServiceExecuteResponse_Output struct {
	Output *ExecuteResponse `protobuf:"bytes,1,opt,name=output,proto3,oneof"` // Standard command output from command.proto
}

type DaemonServiceExecuteResponse_UiRequest struct {
	UiRequest *InteractResponse `protobuf:"bytes,2,opt,name=ui_request,json=uiRequest,proto3,oneof"` // UI interaction request from plugin
}

type DaemonServiceExecuteResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // Connection or orchestration error
}

func (*DaemonServiceExecuteResponse_Output) isDaemonServiceExecuteResponse_Payload() {}

func (*DaemonServiceExecuteResponse_UiRequest) isDaemonServiceExecuteResponse_Payload() {}

func (*DaemonServiceExecuteResponse_Error) isDaemonServiceExecuteResponse_Payload() {}

// CommandRequest initiates a command execution.
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Flags         map[string]string      `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigJson    []byte                 `protobuf:"bytes,5,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	RigVersion    string                 `protobuf:"bytes,6,opt,name=rig_version,json=rigVersion,proto3" json:"rig_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *CommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CommandRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *CommandRequest) GetRigVersion() string {
	if x != nil {
		return x.RigVersion
	}
	return ""
}

type DaemonServiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonServiceStatusRequest) Reset() {
	*x = DaemonServiceStatusRequest{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonServiceStatusRequest) ProtoMessage() {}

func (x *DaemonServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*DaemonServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{3}
}

type DaemonServiceStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion  string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	Plugins        []*PluginStatus        `protobuf:"bytes,4,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DaemonServiceStatusResponse) Reset() {
	*x = DaemonServiceStatusResponse{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonServiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonServiceStatusResponse) ProtoMessage() {}

func (x *DaemonServiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonServiceStatusResponse.ProtoReflect.Descriptor instead.
func (*DaemonServiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *DaemonServiceStatusResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *DaemonServiceStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *DaemonServiceStatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *DaemonServiceStatusResponse) GetPlugins() []*PluginStatus {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type PluginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastUsedUnix  int64                  `protobuf:"varint,3,opt,name=last_used_unix,json=lastUsedUnix,proto3" json:"last_used_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *PluginStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PluginStatus) GetLastUsedUnix() int64 {
	if x != nil {
		return x.LastUsedUnix
	}
	return 0
}

type DaemonServiceShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonServiceShutdownRequest) Reset() {
	*x = DaemonServiceShutdownRequest{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonServiceShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonServiceShutdownRequest) ProtoMessage() {}

func (x *DaemonServiceShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonServiceShutdownRequest.ProtoReflect.Descriptor instead.
func (*DaemonServiceShutdownRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *DaemonServiceShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DaemonServiceShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonServiceShutdownResponse) Reset() {
	*x = DaemonServiceShutdownResponse{}
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonServiceShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonServiceShutdownResponse) ProtoMessage() {}

func (x *DaemonServiceShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonServiceShutdownResponse.ProtoReflect.Descriptor instead.
func (*DaemonServiceShutdownResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *DaemonServiceShutdownResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_pkg_api_v1_daemon_proto protoreflect.FileDescriptor

const file_pkg_api_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/v1/daemon.proto\x12\x06rig.v1\x1a\x18pkg/api/v1/command.proto\x1a\x1cpkg/api/v1/interaction.proto\"\x98\x01\n" +
	"\x1bDaemonServiceExecuteRequest\x122\n" +
	"\acommand\x18\x01 \x01(\v2\x16.rig.v1.CommandRequestH\x00R\acommand\x12:\n" +
	"\vui_response\x18\x02 \x01(\v2\x17.rig.v1.InteractRequestH\x00R\n" +
	"uiResponseB\t\n" +
	"\apayload\"\xaf\x01\n" +
	"\x1cDaemonServiceExecuteResponse\x121\n" +
	"\x06output\x18\x01 \x01(\v2\x17.rig.v1.ExecuteResponseH\x00R\x06output\x129\n" +
	"\n" +
	"ui_request\x18\x02 \x01(\v2\x18.rig.v1.InteractResponseH\x00R\tuiRequest\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"\x9d\x02\n" +
	"\x0eCommandRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x127\n" +
	"\x05flags\x18\x04 \x03(\v2!.rig.v1.CommandRequest.FlagsEntryR\x05flags\x12\x1f\n" +
	"\vconfig_json\x18\x05 \x01(\fR\n" +
	"configJson\x12\x1f\n" +
	"\vrig_version\x18\x06 \x01(\tR\n" +
	"rigVersion\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1c\n" +
	"\x1aDaemonServiceStatusRequest\"\xc4\x01\n" +
	"\x1bDaemonServiceStatusResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\x12.\n" +
	"\aplugins\x18\x04 \x03(\v2\x14.rig.v1.PluginStatusR\aplugins\"`\n" +
	"\fPluginStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\x0elast_used_unix\x18\x03 \x01(\x03R\flastUsedUnix\"4\n" +
	"\x1cDaemonServiceShutdownRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\";\n" +
	"\x1dDaemonServiceShutdownResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\x95\x02\n" +
	"\rDaemonService\x12X\n" +
	"\aExecute\x12#.rig.v1.DaemonServiceExecuteRequest\x1a$.rig.v1.DaemonServiceExecuteResponse(\x010\x01\x12Q\n" +
	"\x06Status\x12\".rig.v1.DaemonServiceStatusRequest\x1a#.rig.v1.DaemonServiceStatusResponse\x12W\n" +
	"\bShutdown\x12$.rig.v1.DaemonServiceShutdownRequest\x1a%.rig.v1.DaemonServiceShutdownResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_daemon_proto_rawDescOnce sync.Once
	file_pkg_api_v1_daemon_proto_rawDescData []byte
)

func file_pkg_api_v1_daemon_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_daemon_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_daemon_proto_rawDesc), len(file_pkg_api_v1_daemon_proto_rawDesc)))
	})
	return file_pkg_api_v1_daemon_proto_rawDescData
}

var file_pkg_api_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_v1_daemon_proto_goTypes = []any{
	(*DaemonServiceExecuteRequest)(nil),   // 0: rig.v1.DaemonServiceExecuteRequest
	(*DaemonServiceExecuteResponse)(nil),  // 1: rig.v1.DaemonServiceExecuteResponse
	(*CommandRequest)(nil),                // 2: rig.v1.CommandRequest
	(*DaemonServiceStatusRequest)(nil),    // 3: rig.v1.DaemonServiceStatusRequest
	(*DaemonServiceStatusResponse)(nil),   // 4: rig.v1.DaemonServiceStatusResponse
	(*PluginStatus)(nil),                  // 5: rig.v1.PluginStatus
	(*DaemonServiceShutdownRequest)(nil),  // 6: rig.v1.DaemonServiceShutdownRequest
	(*DaemonServiceShutdownResponse)(nil), // 7: rig.v1.DaemonServiceShutdownResponse
	nil,                                   // 8: rig.v1.CommandRequest.FlagsEntry
	(*InteractRequest)(nil),               // 9: rig.v1.InteractRequest
	(*ExecuteResponse)(nil),               // 10: rig.v1.ExecuteResponse
	(*InteractResponse)(nil),              // 11: rig.v1.InteractResponse
}
var file_pkg_api_v1_daemon_proto_depIdxs = []int32{
	2,  // 0: rig.v1.DaemonServiceExecuteRequest.command:type_name -> rig.v1.CommandRequest
	9,  // 1: rig.v1.DaemonServiceExecuteRequest.ui_response:type_name -> rig.v1.InteractRequest
	10, // 2: rig.v1.DaemonServiceExecuteResponse.output:type_name -> rig.v1.ExecuteResponse
	11, // 3: rig.v1.DaemonServiceExecuteResponse.ui_request:type_name -> rig.v1.InteractResponse
	8,  // 4: rig.v1.CommandRequest.flags:type_name -> rig.v1.CommandRequest.FlagsEntry
	5,  // 5: rig.v1.DaemonServiceStatusResponse.plugins:type_name -> rig.v1.PluginStatus
	0,  // 6: rig.v1.DaemonService.Execute:input_type -> rig.v1.DaemonServiceExecuteRequest
	3,  // 7: rig.v1.DaemonService.Status:input_type -> rig.v1.DaemonServiceStatusRequest
	6,  // 8: rig.v1.DaemonService.Shutdown:input_type -> rig.v1.DaemonServiceShutdownRequest
	1,  // 9: rig.v1.DaemonService.Execute:output_type -> rig.v1.DaemonServiceExecuteResponse
	4,  // 10: rig.v1.DaemonService.Status:output_type -> rig.v1.DaemonServiceStatusResponse
	7,  // 11: rig.v1.DaemonService.Shutdown:output_type -> rig.v1.DaemonServiceShutdownResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_daemon_proto_init() }
func file_pkg_api_v1_daemon_proto_init() {
	if File_pkg_api_v1_daemon_proto != nil {
		return
	}
	file_pkg_api_v1_command_proto_init()
	file_pkg_api_v1_interaction_proto_init()
	file_pkg_api_v1_daemon_proto_msgTypes[0].OneofWrappers = []any{
		(*DaemonServiceExecuteRequest_Command)(nil),
		(*DaemonServiceExecuteRequest_UiResponse)(nil),
	}
	file_pkg_api_v1_daemon_proto_msgTypes[1].OneofWrappers = []any{
		(*DaemonServiceExecuteResponse_Output)(nil),
		(*DaemonServiceExecuteResponse_UiRequest)(nil),
		(*DaemonServiceExecuteResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_daemon_proto_rawDesc), len(file_pkg_api_v1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_daemon_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_daemon_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_daemon_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_daemon_proto = out.File
	file_pkg_api_v1_daemon_proto_goTypes = nil
	file_pkg_api_v1_daemon_proto_depIdxs = nil
}
