// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/hello.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SayHelloRequest contains the name of the person to greet.
type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_pkg_api_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SayHelloResponse contains the greeting message.
type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_pkg_api_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StreamHelloRequest contains the name of the person to greet for streaming.
type StreamHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHelloRequest) Reset() {
	*x = StreamHelloRequest{}
	mi := &file_pkg_api_v1_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHelloRequest) ProtoMessage() {}

func (x *StreamHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHelloRequest.ProtoReflect.Descriptor instead.
func (*StreamHelloRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_hello_proto_rawDescGZIP(), []int{2}
}

func (x *StreamHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// StreamHelloResponse contains the greeting message for streaming.
type StreamHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHelloResponse) Reset() {
	*x = StreamHelloResponse{}
	mi := &file_pkg_api_v1_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHelloResponse) ProtoMessage() {}

func (x *StreamHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHelloResponse.ProtoReflect.Descriptor instead.
func (*StreamHelloResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_hello_proto_rawDescGZIP(), []int{3}
}

func (x *StreamHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_v1_hello_proto protoreflect.FileDescriptor

const file_pkg_api_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/api/v1/hello.proto\x12\x06rig.v1\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\x12StreamHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13StreamHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x99\x01\n" +
	"\x0eGreeterService\x12=\n" +
	"\bSayHello\x12\x17.rig.v1.SayHelloRequest\x1a\x18.rig.v1.SayHelloResponse\x12H\n" +
	"\vStreamHello\x12\x1a.rig.v1.StreamHelloRequest\x1a\x1b.rig.v1.StreamHelloResponse0\x01B'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_hello_proto_rawDescOnce sync.Once
	file_pkg_api_v1_hello_proto_rawDescData []byte
)

func file_pkg_api_v1_hello_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_hello_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_hello_proto_rawDesc), len(file_pkg_api_v1_hello_proto_rawDesc)))
	})
	return file_pkg_api_v1_hello_proto_rawDescData
}

var file_pkg_api_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_v1_hello_proto_goTypes = []any{
	(*SayHelloRequest)(nil),     // 0: rig.v1.SayHelloRequest
	(*SayHelloResponse)(nil),    // 1: rig.v1.SayHelloResponse
	(*StreamHelloRequest)(nil),  // 2: rig.v1.StreamHelloRequest
	(*StreamHelloResponse)(nil), // 3: rig.v1.StreamHelloResponse
}
var file_pkg_api_v1_hello_proto_depIdxs = []int32{
	0, // 0: rig.v1.GreeterService.SayHello:input_type -> rig.v1.SayHelloRequest
	2, // 1: rig.v1.GreeterService.StreamHello:input_type -> rig.v1.StreamHelloRequest
	1, // 2: rig.v1.GreeterService.SayHello:output_type -> rig.v1.SayHelloResponse
	3, // 3: rig.v1.GreeterService.StreamHello:output_type -> rig.v1.StreamHelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_hello_proto_init() }
func file_pkg_api_v1_hello_proto_init() {
	if File_pkg_api_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_hello_proto_rawDesc), len(file_pkg_api_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_hello_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_hello_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_hello_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_hello_proto = out.File
	file_pkg_api_v1_hello_proto_goTypes = nil
	file_pkg_api_v1_hello_proto_depIdxs = nil
}
