// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/interaction.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// type determines how the progress is displayed.
type ProgressUpdate_Type int32

const (
	ProgressUpdate_TYPE_UNSPECIFIED ProgressUpdate_Type = 0 // Default unspecified status
	ProgressUpdate_TYPE_STATUS      ProgressUpdate_Type = 1 // Simple text status update
	ProgressUpdate_TYPE_SPINNER     ProgressUpdate_Type = 2 // Display a spinner with the message
	ProgressUpdate_TYPE_BAR         ProgressUpdate_Type = 3 // Display a progress bar
)

// Enum value maps for ProgressUpdate_Type.
var (
	ProgressUpdate_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_STATUS",
		2: "TYPE_SPINNER",
		3: "TYPE_BAR",
	}
	ProgressUpdate_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_STATUS":      1,
		"TYPE_SPINNER":     2,
		"TYPE_BAR":         3,
	}
)

func (x ProgressUpdate_Type) Enum() *ProgressUpdate_Type {
	p := new(ProgressUpdate_Type)
	*p = x
	return p
}

func (x ProgressUpdate_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressUpdate_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_interaction_proto_enumTypes[0].Descriptor()
}

func (ProgressUpdate_Type) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_interaction_proto_enumTypes[0]
}

func (x ProgressUpdate_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressUpdate_Type.Descriptor instead.
func (ProgressUpdate_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{8, 0}
}

// InteractionRequest is sent from the Plugin to the Host to request
// UI interactions or report progress.
type InteractResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique identifier for this request/response pair.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*InteractResponse_Prompt
	//	*InteractResponse_Confirm
	//	*InteractResponse_Select
	//	*InteractResponse_Progress
	Payload       isInteractResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractResponse) Reset() {
	*x = InteractResponse{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractResponse) ProtoMessage() {}

func (x *InteractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractResponse.ProtoReflect.Descriptor instead.
func (*InteractResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *InteractResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InteractResponse) GetPayload() isInteractResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InteractResponse) GetPrompt() *PromptRequest {
	if x != nil {
		if x, ok := x.Payload.(*InteractResponse_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *InteractResponse) GetConfirm() *ConfirmRequest {
	if x != nil {
		if x, ok := x.Payload.(*InteractResponse_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

func (x *InteractResponse) GetSelect() *SelectRequest {
	if x != nil {
		if x, ok := x.Payload.(*InteractResponse_Select); ok {
			return x.Select
		}
	}
	return nil
}

func (x *InteractResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*InteractResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isInteractResponse_Payload interface {
	isInteractResponse_Payload()
}

type InteractResponse_Prompt struct {
	Prompt *PromptRequest `protobuf:"bytes,2,opt,name=prompt,proto3,oneof"`
}

type InteractResponse_Confirm struct {
	Confirm *ConfirmRequest `protobuf:"bytes,3,opt,name=confirm,proto3,oneof"`
}

type InteractResponse_Select struct {
	Select *SelectRequest `protobuf:"bytes,4,opt,name=select,proto3,oneof"`
}

type InteractResponse_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,5,opt,name=progress,proto3,oneof"`
}

func (*InteractResponse_Prompt) isInteractResponse_Payload() {}

func (*InteractResponse_Confirm) isInteractResponse_Payload() {}

func (*InteractResponse_Select) isInteractResponse_Payload() {}

func (*InteractResponse_Progress) isInteractResponse_Payload() {}

type InteractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// response_to matches the id of the InteractResponse.
	ResponseTo string `protobuf:"bytes,1,opt,name=response_to,json=responseTo,proto3" json:"response_to,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*InteractRequest_Prompt
	//	*InteractRequest_Confirm
	//	*InteractRequest_Select
	Payload       isInteractRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRequest) Reset() {
	*x = InteractRequest{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRequest) ProtoMessage() {}

func (x *InteractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRequest.ProtoReflect.Descriptor instead.
func (*InteractRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *InteractRequest) GetResponseTo() string {
	if x != nil {
		return x.ResponseTo
	}
	return ""
}

func (x *InteractRequest) GetPayload() isInteractRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InteractRequest) GetPrompt() *PromptResponse {
	if x != nil {
		if x, ok := x.Payload.(*InteractRequest_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *InteractRequest) GetConfirm() *ConfirmResponse {
	if x != nil {
		if x, ok := x.Payload.(*InteractRequest_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

func (x *InteractRequest) GetSelect() *SelectResponse {
	if x != nil {
		if x, ok := x.Payload.(*InteractRequest_Select); ok {
			return x.Select
		}
	}
	return nil
}

type isInteractRequest_Payload interface {
	isInteractRequest_Payload()
}

type InteractRequest_Prompt struct {
	Prompt *PromptResponse `protobuf:"bytes,2,opt,name=prompt,proto3,oneof"`
}

type InteractRequest_Confirm struct {
	Confirm *ConfirmResponse `protobuf:"bytes,3,opt,name=confirm,proto3,oneof"`
}

type InteractRequest_Select struct {
	Select *SelectResponse `protobuf:"bytes,4,opt,name=select,proto3,oneof"`
}

func (*InteractRequest_Prompt) isInteractRequest_Payload() {}

func (*InteractRequest_Confirm) isInteractRequest_Payload() {}

func (*InteractRequest_Select) isInteractRequest_Payload() {}

// PromptRequest asks the user for a text input.
type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder   string                 `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Sensitive     bool                   `protobuf:"varint,4,opt,name=sensitive,proto3" json:"sensitive,omitempty"` // If true, input should be masked (e.g., password)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *PromptRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PromptRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *PromptRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *PromptRequest) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

// PromptResponse contains the text entered by the user.
type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *PromptResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ConfirmRequest asks the user for a yes/no confirmation.
type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	DefaultValue  bool                   `protobuf:"varint,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfirmRequest) GetDefaultValue() bool {
	if x != nil {
		return x.DefaultValue
	}
	return false
}

// ConfirmResponse contains the user's choice.
type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

// SelectRequest asks the user to choose from a list of options.
type SelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	Multiselect   bool                   `protobuf:"varint,3,opt,name=multiselect,proto3" json:"multiselect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRequest) Reset() {
	*x = SelectRequest{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequest) ProtoMessage() {}

func (x *SelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequest.ProtoReflect.Descriptor instead.
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *SelectRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SelectRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SelectRequest) GetMultiselect() bool {
	if x != nil {
		return x.Multiselect
	}
	return false
}

// SelectResponse contains the indices of the selected options.
type SelectResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SelectedIndices []int32                `protobuf:"varint,1,rep,packed,name=selected_indices,json=selectedIndices,proto3" json:"selected_indices,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SelectResponse) Reset() {
	*x = SelectResponse{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectResponse) ProtoMessage() {}

func (x *SelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectResponse.ProtoReflect.Descriptor instead.
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *SelectResponse) GetSelectedIndices() []int32 {
	if x != nil {
		return x.SelectedIndices
	}
	return nil
}

// ProgressUpdate provides real-time status updates for a long-running task.
type ProgressUpdate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type    ProgressUpdate_Type    `protobuf:"varint,2,opt,name=type,proto3,enum=rig.v1.ProgressUpdate_Type" json:"type,omitempty"`
	// progress is the completion percentage (0-100), used for BAR type.
	Progress int32 `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	// indeterminate is true if the total progress is unknown.
	Indeterminate bool `protobuf:"varint,4,opt,name=indeterminate,proto3" json:"indeterminate,omitempty"`
	// done is true if the progress is complete.
	Done          bool `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetType() ProgressUpdate_Type {
	if x != nil {
		return x.Type
	}
	return ProgressUpdate_TYPE_UNSPECIFIED
}

func (x *ProgressUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressUpdate) GetIndeterminate() bool {
	if x != nil {
		return x.Indeterminate
	}
	return false
}

func (x *ProgressUpdate) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_pkg_api_v1_interaction_proto protoreflect.FileDescriptor

const file_pkg_api_v1_interaction_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/api/v1/interaction.proto\x12\x06rig.v1\"\xf9\x01\n" +
	"\x10InteractResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06prompt\x18\x02 \x01(\v2\x15.rig.v1.PromptRequestH\x00R\x06prompt\x122\n" +
	"\aconfirm\x18\x03 \x01(\v2\x16.rig.v1.ConfirmRequestH\x00R\aconfirm\x12/\n" +
	"\x06select\x18\x04 \x01(\v2\x15.rig.v1.SelectRequestH\x00R\x06select\x124\n" +
	"\bprogress\x18\x05 \x01(\v2\x16.rig.v1.ProgressUpdateH\x00R\bprogressB\t\n" +
	"\apayload\"\xd6\x01\n" +
	"\x0fInteractRequest\x12\x1f\n" +
	"\vresponse_to\x18\x01 \x01(\tR\n" +
	"responseTo\x120\n" +
	"\x06prompt\x18\x02 \x01(\v2\x16.rig.v1.PromptResponseH\x00R\x06prompt\x123\n" +
	"\aconfirm\x18\x03 \x01(\v2\x17.rig.v1.ConfirmResponseH\x00R\aconfirm\x120\n" +
	"\x06select\x18\x04 \x01(\v2\x16.rig.v1.SelectResponseH\x00R\x06selectB\t\n" +
	"\apayload\"\x8a\x01\n" +
	"\rPromptRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x02 \x01(\tR\vplaceholder\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\tR\fdefaultValue\x12\x1c\n" +
	"\tsensitive\x18\x04 \x01(\bR\tsensitive\"&\n" +
	"\x0ePromptResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"K\n" +
	"\x0eConfirmRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\bR\fdefaultValue\"/\n" +
	"\x0fConfirmResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed\"a\n" +
	"\rSelectRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12 \n" +
	"\vmultiselect\x18\x03 \x01(\bR\vmultiselect\";\n" +
	"\x0eSelectResponse\x12)\n" +
	"\x10selected_indices\x18\x01 \x03(\x05R\x0fselectedIndices\"\x80\x02\n" +
	"\x0eProgressUpdate\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.rig.v1.ProgressUpdate.TypeR\x04type\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12$\n" +
	"\rindeterminate\x18\x04 \x01(\bR\rindeterminate\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"M\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_STATUS\x10\x01\x12\x10\n" +
	"\fTYPE_SPINNER\x10\x02\x12\f\n" +
	"\bTYPE_BAR\x10\x03B'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_interaction_proto_rawDescOnce sync.Once
	file_pkg_api_v1_interaction_proto_rawDescData []byte
)

func file_pkg_api_v1_interaction_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_interaction_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_interaction_proto_rawDesc), len(file_pkg_api_v1_interaction_proto_rawDesc)))
	})
	return file_pkg_api_v1_interaction_proto_rawDescData
}

var file_pkg_api_v1_interaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_v1_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_v1_interaction_proto_goTypes = []any{
	(ProgressUpdate_Type)(0), // 0: rig.v1.ProgressUpdate.Type
	(*InteractResponse)(nil), // 1: rig.v1.InteractResponse
	(*InteractRequest)(nil),  // 2: rig.v1.InteractRequest
	(*PromptRequest)(nil),    // 3: rig.v1.PromptRequest
	(*PromptResponse)(nil),   // 4: rig.v1.PromptResponse
	(*ConfirmRequest)(nil),   // 5: rig.v1.ConfirmRequest
	(*ConfirmResponse)(nil),  // 6: rig.v1.ConfirmResponse
	(*SelectRequest)(nil),    // 7: rig.v1.SelectRequest
	(*SelectResponse)(nil),   // 8: rig.v1.SelectResponse
	(*ProgressUpdate)(nil),   // 9: rig.v1.ProgressUpdate
}
var file_pkg_api_v1_interaction_proto_depIdxs = []int32{
	3, // 0: rig.v1.InteractResponse.prompt:type_name -> rig.v1.PromptRequest
	5, // 1: rig.v1.InteractResponse.confirm:type_name -> rig.v1.ConfirmRequest
	7, // 2: rig.v1.InteractResponse.select:type_name -> rig.v1.SelectRequest
	9, // 3: rig.v1.InteractResponse.progress:type_name -> rig.v1.ProgressUpdate
	4, // 4: rig.v1.InteractRequest.prompt:type_name -> rig.v1.PromptResponse
	6, // 5: rig.v1.InteractRequest.confirm:type_name -> rig.v1.ConfirmResponse
	8, // 6: rig.v1.InteractRequest.select:type_name -> rig.v1.SelectResponse
	0, // 7: rig.v1.ProgressUpdate.type:type_name -> rig.v1.ProgressUpdate.Type
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_interaction_proto_init() }
func file_pkg_api_v1_interaction_proto_init() {
	if File_pkg_api_v1_interaction_proto != nil {
		return
	}
	file_pkg_api_v1_interaction_proto_msgTypes[0].OneofWrappers = []any{
		(*InteractResponse_Prompt)(nil),
		(*InteractResponse_Confirm)(nil),
		(*InteractResponse_Select)(nil),
		(*InteractResponse_Progress)(nil),
	}
	file_pkg_api_v1_interaction_proto_msgTypes[1].OneofWrappers = []any{
		(*InteractRequest_Prompt)(nil),
		(*InteractRequest_Confirm)(nil),
		(*InteractRequest_Select)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_interaction_proto_rawDesc), len(file_pkg_api_v1_interaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_v1_interaction_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_interaction_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_interaction_proto_enumTypes,
		MessageInfos:      file_pkg_api_v1_interaction_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_interaction_proto = out.File
	file_pkg_api_v1_interaction_proto_goTypes = nil
	file_pkg_api_v1_interaction_proto_depIdxs = nil
}
