// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/api/v1/knowledge.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeService_CreateTicketNote_FullMethodName = "/rig.v1.KnowledgeService/CreateTicketNote"
	KnowledgeService_UpdateDailyNote_FullMethodName  = "/rig.v1.KnowledgeService/UpdateDailyNote"
	KnowledgeService_GetNotePath_FullMethodName      = "/rig.v1.KnowledgeService/GetNotePath"
	KnowledgeService_GetDailyNotePath_FullMethodName = "/rig.v1.KnowledgeService/GetDailyNotePath"
)

// KnowledgeServiceClient is the client API for KnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KnowledgeService defines the interface for knowledge management operations (Notes, Obsidian, etc.)
type KnowledgeServiceClient interface {
	// CreateTicketNote creates a new ticket note and returns its path.
	CreateTicketNote(ctx context.Context, in *CreateTicketNoteRequest, opts ...grpc.CallOption) (*CreateTicketNoteResponse, error)
	// UpdateDailyNote updates the daily note with a log entry.
	UpdateDailyNote(ctx context.Context, in *UpdateDailyNoteRequest, opts ...grpc.CallOption) (*UpdateDailyNoteResponse, error)
	// GetNotePath retrieves the path for a ticket note without creating it.
	GetNotePath(ctx context.Context, in *GetNotePathRequest, opts ...grpc.CallOption) (*GetNotePathResponse, error)
	// GetDailyNotePath retrieves the path for today's daily note.
	GetDailyNotePath(ctx context.Context, in *GetDailyNotePathRequest, opts ...grpc.CallOption) (*GetDailyNotePathResponse, error)
}

type knowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeServiceClient(cc grpc.ClientConnInterface) KnowledgeServiceClient {
	return &knowledgeServiceClient{cc}
}

func (c *knowledgeServiceClient) CreateTicketNote(ctx context.Context, in *CreateTicketNoteRequest, opts ...grpc.CallOption) (*CreateTicketNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTicketNoteResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_CreateTicketNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UpdateDailyNote(ctx context.Context, in *UpdateDailyNoteRequest, opts ...grpc.CallOption) (*UpdateDailyNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDailyNoteResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_UpdateDailyNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetNotePath(ctx context.Context, in *GetNotePathRequest, opts ...grpc.CallOption) (*GetNotePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotePathResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetNotePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetDailyNotePath(ctx context.Context, in *GetDailyNotePathRequest, opts ...grpc.CallOption) (*GetDailyNotePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyNotePathResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetDailyNotePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServiceServer is the server API for KnowledgeService service.
// All implementations must embed UnimplementedKnowledgeServiceServer
// for forward compatibility.
//
// KnowledgeService defines the interface for knowledge management operations (Notes, Obsidian, etc.)
type KnowledgeServiceServer interface {
	// CreateTicketNote creates a new ticket note and returns its path.
	CreateTicketNote(context.Context, *CreateTicketNoteRequest) (*CreateTicketNoteResponse, error)
	// UpdateDailyNote updates the daily note with a log entry.
	UpdateDailyNote(context.Context, *UpdateDailyNoteRequest) (*UpdateDailyNoteResponse, error)
	// GetNotePath retrieves the path for a ticket note without creating it.
	GetNotePath(context.Context, *GetNotePathRequest) (*GetNotePathResponse, error)
	// GetDailyNotePath retrieves the path for today's daily note.
	GetDailyNotePath(context.Context, *GetDailyNotePathRequest) (*GetDailyNotePathResponse, error)
	mustEmbedUnimplementedKnowledgeServiceServer()
}

// UnimplementedKnowledgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServiceServer struct{}

func (UnimplementedKnowledgeServiceServer) CreateTicketNote(context.Context, *CreateTicketNoteRequest) (*CreateTicketNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTicketNote not implemented")
}
func (UnimplementedKnowledgeServiceServer) UpdateDailyNote(context.Context, *UpdateDailyNoteRequest) (*UpdateDailyNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDailyNote not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetNotePath(context.Context, *GetNotePathRequest) (*GetNotePathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotePath not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetDailyNotePath(context.Context, *GetDailyNotePathRequest) (*GetDailyNotePathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyNotePath not implemented")
}
func (UnimplementedKnowledgeServiceServer) mustEmbedUnimplementedKnowledgeServiceServer() {}
func (UnimplementedKnowledgeServiceServer) testEmbeddedByValue()                          {}

// UnsafeKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServiceServer will
// result in compilation errors.
type UnsafeKnowledgeServiceServer interface {
	mustEmbedUnimplementedKnowledgeServiceServer()
}

func RegisterKnowledgeServiceServer(s grpc.ServiceRegistrar, srv KnowledgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeService_ServiceDesc, srv)
}

func _KnowledgeService_CreateTicketNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreateTicketNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreateTicketNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreateTicketNote(ctx, req.(*CreateTicketNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UpdateDailyNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDailyNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UpdateDailyNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UpdateDailyNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UpdateDailyNote(ctx, req.(*UpdateDailyNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetNotePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetNotePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetNotePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetNotePath(ctx, req.(*GetNotePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetDailyNotePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyNotePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetDailyNotePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetDailyNotePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetDailyNotePath(ctx, req.(*GetDailyNotePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeService_ServiceDesc is the grpc.ServiceDesc for KnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rig.v1.KnowledgeService",
	HandlerType: (*KnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicketNote",
			Handler:    _KnowledgeService_CreateTicketNote_Handler,
		},
		{
			MethodName: "UpdateDailyNote",
			Handler:    _KnowledgeService_UpdateDailyNote_Handler,
		},
		{
			MethodName: "GetNotePath",
			Handler:    _KnowledgeService_GetNotePath_Handler,
		},
		{
			MethodName: "GetDailyNotePath",
			Handler:    _KnowledgeService_GetDailyNotePath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/v1/knowledge.proto",
}
