// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/knowledge.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NoteMetadata carries all information needed to render a ticket note.
type NoteMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	TicketType    string                 `protobuf:"bytes,2,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	RepoName      string                 `protobuf:"bytes,6,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoPath      string                 `protobuf:"bytes,7,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,8,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	Date          string                 `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,10,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteMetadata) Reset() {
	*x = NoteMetadata{}
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteMetadata) ProtoMessage() {}

func (x *NoteMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteMetadata.ProtoReflect.Descriptor instead.
func (*NoteMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *NoteMetadata) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *NoteMetadata) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *NoteMetadata) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *NoteMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NoteMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NoteMetadata) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *NoteMetadata) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *NoteMetadata) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

func (x *NoteMetadata) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *NoteMetadata) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type CreateTicketNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *NoteMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketNoteRequest) Reset() {
	*x = CreateTicketNoteRequest{}
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketNoteRequest) ProtoMessage() {}

func (x *CreateTicketNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketNoteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketNoteRequest) GetMetadata() *NoteMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateTicketNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketNoteResponse) Reset() {
	*x = CreateTicketNoteResponse{}
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketNoteResponse) ProtoMessage() {}

func (x *CreateTicketNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateTicketNoteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTicketNoteResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateTicketNoteResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type UpdateDailyNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	TicketType    string                 `protobuf:"bytes,2,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDailyNoteRequest) Reset() {
	*x = UpdateDailyNoteRequest{}
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDailyNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDailyNoteRequest) ProtoMessage() {}

func (x *UpdateDailyNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDailyNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateDailyNoteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDailyNoteRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *UpdateDailyNoteRequest) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

type UpdateDailyNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDailyNoteResponse) Reset() {
	*x = UpdateDailyNoteResponse{}
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDailyNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDailyNoteResponse) ProtoMessage() {}

func (x *UpdateDailyNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDailyNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateDailyNoteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDailyNoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNotePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	TicketType    string                 `protobuf:"bytes,2,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotePathRequest) Reset() {
	*x = GetNotePathRequest{}
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotePathRequest) ProtoMessage() {}

func (x *GetNotePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotePathRequest.ProtoReflect.Descriptor instead.
func (*GetNotePathRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *GetNotePathRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *GetNotePathRequest) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

type GetNotePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotePathResponse) Reset() {
	*x = GetNotePathResponse{}
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotePathResponse) ProtoMessage() {}

func (x *GetNotePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotePathResponse.ProtoReflect.Descriptor instead.
func (*GetNotePathResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotePathResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_pkg_api_v1_knowledge_proto protoreflect.FileDescriptor

const file_pkg_api_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/api/v1/knowledge.proto\x12\x06rig.v1\"\xa7\x02\n" +
	"\fNoteMetadata\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1f\n" +
	"\vticket_type\x18\x02 \x01(\tR\n" +
	"ticketType\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\trepo_name\x18\x06 \x01(\tR\brepoName\x12\x1b\n" +
	"\trepo_path\x18\a \x01(\tR\brepoPath\x12#\n" +
	"\rworktree_path\x18\b \x01(\tR\fworktreePath\x12\x12\n" +
	"\x04date\x18\t \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\n" +
	" \x01(\tR\x04time\"K\n" +
	"\x17CreateTicketNoteRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.rig.v1.NoteMetadataR\bmetadata\"H\n" +
	"\x18CreateTicketNoteResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"V\n" +
	"\x16UpdateDailyNoteRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1f\n" +
	"\vticket_type\x18\x02 \x01(\tR\n" +
	"ticketType\"3\n" +
	"\x17UpdateDailyNoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x12GetNotePathRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1f\n" +
	"\vticket_type\x18\x02 \x01(\tR\n" +
	"ticketType\")\n" +
	"\x13GetNotePathResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path2\x85\x02\n" +
	"\x10KnowledgeService\x12U\n" +
	"\x10CreateTicketNote\x12\x1f.rig.v1.CreateTicketNoteRequest\x1a .rig.v1.CreateTicketNoteResponse\x12R\n" +
	"\x0fUpdateDailyNote\x12\x1e.rig.v1.UpdateDailyNoteRequest\x1a\x1f.rig.v1.UpdateDailyNoteResponse\x12F\n" +
	"\vGetNotePath\x12\x1a.rig.v1.GetNotePathRequest\x1a\x1b.rig.v1.GetNotePathResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_knowledge_proto_rawDescOnce sync.Once
	file_pkg_api_v1_knowledge_proto_rawDescData []byte
)

func file_pkg_api_v1_knowledge_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_knowledge_proto_rawDesc), len(file_pkg_api_v1_knowledge_proto_rawDesc)))
	})
	return file_pkg_api_v1_knowledge_proto_rawDescData
}

var file_pkg_api_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_api_v1_knowledge_proto_goTypes = []any{
	(*NoteMetadata)(nil),             // 0: rig.v1.NoteMetadata
	(*CreateTicketNoteRequest)(nil),  // 1: rig.v1.CreateTicketNoteRequest
	(*CreateTicketNoteResponse)(nil), // 2: rig.v1.CreateTicketNoteResponse
	(*UpdateDailyNoteRequest)(nil),   // 3: rig.v1.UpdateDailyNoteRequest
	(*UpdateDailyNoteResponse)(nil),  // 4: rig.v1.UpdateDailyNoteResponse
	(*GetNotePathRequest)(nil),       // 5: rig.v1.GetNotePathRequest
	(*GetNotePathResponse)(nil),      // 6: rig.v1.GetNotePathResponse
}
var file_pkg_api_v1_knowledge_proto_depIdxs = []int32{
	0, // 0: rig.v1.CreateTicketNoteRequest.metadata:type_name -> rig.v1.NoteMetadata
	1, // 1: rig.v1.KnowledgeService.CreateTicketNote:input_type -> rig.v1.CreateTicketNoteRequest
	3, // 2: rig.v1.KnowledgeService.UpdateDailyNote:input_type -> rig.v1.UpdateDailyNoteRequest
	5, // 3: rig.v1.KnowledgeService.GetNotePath:input_type -> rig.v1.GetNotePathRequest
	2, // 4: rig.v1.KnowledgeService.CreateTicketNote:output_type -> rig.v1.CreateTicketNoteResponse
	4, // 5: rig.v1.KnowledgeService.UpdateDailyNote:output_type -> rig.v1.UpdateDailyNoteResponse
	6, // 6: rig.v1.KnowledgeService.GetNotePath:output_type -> rig.v1.GetNotePathResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_knowledge_proto_init() }
func file_pkg_api_v1_knowledge_proto_init() {
	if File_pkg_api_v1_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_knowledge_proto_rawDesc), len(file_pkg_api_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_knowledge_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_knowledge_proto = out.File
	file_pkg_api_v1_knowledge_proto_goTypes = nil
	file_pkg_api_v1_knowledge_proto_depIdxs = nil
}
