// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/node.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteNodeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeId   string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	// config_json is the plugin-specific configuration for this node.
	ConfigJson []byte `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// inputs is a map of input names to JSON-serialized values from upstream nodes.
	Inputs map[string][]byte `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// secrets is a map of explicitly granted secrets (Key -> Value).
	Secrets map[string]string `protobuf:"bytes,5,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// workspace is the absolute path to the node's isolated working directory.
	Workspace     string `protobuf:"bytes,6,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteNodeRequest) Reset() {
	*x = ExecuteNodeRequest{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNodeRequest) ProtoMessage() {}

func (x *ExecuteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteNodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteNodeRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ExecuteNodeRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ExecuteNodeRequest) GetInputs() map[string][]byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecuteNodeRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ExecuteNodeRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type ExecuteNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// output is the JSON-serialized result of the node's execution.
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// error_message is populated if the execution failed.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteNodeResponse) Reset() {
	*x = ExecuteNodeResponse{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNodeResponse) ProtoMessage() {}

func (x *ExecuteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteNodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteNodeResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"` // File mode/permissions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{5}
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Entries       []*ListDirResponse_FileInfo `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *ListDirResponse) GetEntries() []*ListDirResponse_FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type HttpRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequestRequest) Reset() {
	*x = HttpRequestRequest{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequestRequest) ProtoMessage() {}

func (x *HttpRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequestRequest.ProtoReflect.Descriptor instead.
func (*HttpRequestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *HttpRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequestRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpRequestRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequestRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequestResponse) Reset() {
	*x = HttpRequestResponse{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequestResponse) ProtoMessage() {}

func (x *HttpRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequestResponse.ProtoReflect.Descriptor instead.
func (*HttpRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *HttpRequestResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpRequestResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequestResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ListDirResponse_FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse_FileInfo) Reset() {
	*x = ListDirResponse_FileInfo{}
	mi := &file_pkg_api_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse_FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse_FileInfo) ProtoMessage() {}

func (x *ListDirResponse_FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse_FileInfo.ProtoReflect.Descriptor instead.
func (*ListDirResponse_FileInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_node_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListDirResponse_FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDirResponse_FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *ListDirResponse_FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_pkg_api_v1_node_proto protoreflect.FileDescriptor

const file_pkg_api_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/api/v1/node.proto\x12\x06rig.v1\"\x83\x03\n" +
	"\x12ExecuteNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\x12>\n" +
	"\x06inputs\x18\x04 \x03(\v2&.rig.v1.ExecuteNodeRequest.InputsEntryR\x06inputs\x12A\n" +
	"\asecrets\x18\x05 \x03(\v2'.rig.v1.ExecuteNodeRequest.SecretsEntryR\asecrets\x12\x1c\n" +
	"\tworkspace\x18\x06 \x01(\tR\tworkspace\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x13ExecuteNodeResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"T\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"\x13\n" +
	"\x11WriteFileResponse\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x98\x01\n" +
	"\x0fListDirResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .rig.v1.ListDirResponse.FileInfoR\aentries\x1aI\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xd1\x01\n" +
	"\x12HttpRequestRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.rig.v1.HttpRequestRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\x13HttpRequestResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12B\n" +
	"\aheaders\x18\x02 \x03(\v2(.rig.v1.HttpRequestResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012^\n" +
	"\x14NodeExecutionService\x12F\n" +
	"\vExecuteNode\x12\x1a.rig.v1.ExecuteNodeRequest\x1a\x1b.rig.v1.ExecuteNodeResponse2\x96\x02\n" +
	"\x0fResourceService\x12=\n" +
	"\bReadFile\x12\x17.rig.v1.ReadFileRequest\x1a\x18.rig.v1.ReadFileResponse\x12@\n" +
	"\tWriteFile\x12\x18.rig.v1.WriteFileRequest\x1a\x19.rig.v1.WriteFileResponse\x12:\n" +
	"\aListDir\x12\x16.rig.v1.ListDirRequest\x1a\x17.rig.v1.ListDirResponse\x12F\n" +
	"\vHttpRequest\x12\x1a.rig.v1.HttpRequestRequest\x1a\x1b.rig.v1.HttpRequestResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_node_proto_rawDescOnce sync.Once
	file_pkg_api_v1_node_proto_rawDescData []byte
)

func file_pkg_api_v1_node_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_node_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_node_proto_rawDesc), len(file_pkg_api_v1_node_proto_rawDesc)))
	})
	return file_pkg_api_v1_node_proto_rawDescData
}

var file_pkg_api_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_api_v1_node_proto_goTypes = []any{
	(*ExecuteNodeRequest)(nil),       // 0: rig.v1.ExecuteNodeRequest
	(*ExecuteNodeResponse)(nil),      // 1: rig.v1.ExecuteNodeResponse
	(*ReadFileRequest)(nil),          // 2: rig.v1.ReadFileRequest
	(*ReadFileResponse)(nil),         // 3: rig.v1.ReadFileResponse
	(*WriteFileRequest)(nil),         // 4: rig.v1.WriteFileRequest
	(*WriteFileResponse)(nil),        // 5: rig.v1.WriteFileResponse
	(*ListDirRequest)(nil),           // 6: rig.v1.ListDirRequest
	(*ListDirResponse)(nil),          // 7: rig.v1.ListDirResponse
	(*HttpRequestRequest)(nil),       // 8: rig.v1.HttpRequestRequest
	(*HttpRequestResponse)(nil),      // 9: rig.v1.HttpRequestResponse
	nil,                              // 10: rig.v1.ExecuteNodeRequest.InputsEntry
	nil,                              // 11: rig.v1.ExecuteNodeRequest.SecretsEntry
	(*ListDirResponse_FileInfo)(nil), // 12: rig.v1.ListDirResponse.FileInfo
	nil,                              // 13: rig.v1.HttpRequestRequest.HeadersEntry
	nil,                              // 14: rig.v1.HttpRequestResponse.HeadersEntry
}
var file_pkg_api_v1_node_proto_depIdxs = []int32{
	10, // 0: rig.v1.ExecuteNodeRequest.inputs:type_name -> rig.v1.ExecuteNodeRequest.InputsEntry
	11, // 1: rig.v1.ExecuteNodeRequest.secrets:type_name -> rig.v1.ExecuteNodeRequest.SecretsEntry
	12, // 2: rig.v1.ListDirResponse.entries:type_name -> rig.v1.ListDirResponse.FileInfo
	13, // 3: rig.v1.HttpRequestRequest.headers:type_name -> rig.v1.HttpRequestRequest.HeadersEntry
	14, // 4: rig.v1.HttpRequestResponse.headers:type_name -> rig.v1.HttpRequestResponse.HeadersEntry
	0,  // 5: rig.v1.NodeExecutionService.ExecuteNode:input_type -> rig.v1.ExecuteNodeRequest
	2,  // 6: rig.v1.ResourceService.ReadFile:input_type -> rig.v1.ReadFileRequest
	4,  // 7: rig.v1.ResourceService.WriteFile:input_type -> rig.v1.WriteFileRequest
	6,  // 8: rig.v1.ResourceService.ListDir:input_type -> rig.v1.ListDirRequest
	8,  // 9: rig.v1.ResourceService.HttpRequest:input_type -> rig.v1.HttpRequestRequest
	1,  // 10: rig.v1.NodeExecutionService.ExecuteNode:output_type -> rig.v1.ExecuteNodeResponse
	3,  // 11: rig.v1.ResourceService.ReadFile:output_type -> rig.v1.ReadFileResponse
	5,  // 12: rig.v1.ResourceService.WriteFile:output_type -> rig.v1.WriteFileResponse
	7,  // 13: rig.v1.ResourceService.ListDir:output_type -> rig.v1.ListDirResponse
	9,  // 14: rig.v1.ResourceService.HttpRequest:output_type -> rig.v1.HttpRequestResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_node_proto_init() }
func file_pkg_api_v1_node_proto_init() {
	if File_pkg_api_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_node_proto_rawDesc), len(file_pkg_api_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_api_v1_node_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_node_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_node_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_node_proto = out.File
	file_pkg_api_v1_node_proto_goTypes = nil
	file_pkg_api_v1_node_proto_depIdxs = nil
}
