// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/api/v1/node.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeExecutionService_ExecuteNode_FullMethodName = "/rig.v1.NodeExecutionService/ExecuteNode"
)

// NodeExecutionServiceClient is the client API for NodeExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeExecutionService is implemented by plugins that can execute workflow nodes.
type NodeExecutionServiceClient interface {
	// ExecuteNode runs a single node in a workflow.
	ExecuteNode(ctx context.Context, in *ExecuteNodeRequest, opts ...grpc.CallOption) (*ExecuteNodeResponse, error)
}

type nodeExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeExecutionServiceClient(cc grpc.ClientConnInterface) NodeExecutionServiceClient {
	return &nodeExecutionServiceClient{cc}
}

func (c *nodeExecutionServiceClient) ExecuteNode(ctx context.Context, in *ExecuteNodeRequest, opts ...grpc.CallOption) (*ExecuteNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteNodeResponse)
	err := c.cc.Invoke(ctx, NodeExecutionService_ExecuteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeExecutionServiceServer is the server API for NodeExecutionService service.
// All implementations must embed UnimplementedNodeExecutionServiceServer
// for forward compatibility.
//
// NodeExecutionService is implemented by plugins that can execute workflow nodes.
type NodeExecutionServiceServer interface {
	// ExecuteNode runs a single node in a workflow.
	ExecuteNode(context.Context, *ExecuteNodeRequest) (*ExecuteNodeResponse, error)
	mustEmbedUnimplementedNodeExecutionServiceServer()
}

// UnimplementedNodeExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeExecutionServiceServer struct{}

func (UnimplementedNodeExecutionServiceServer) ExecuteNode(context.Context, *ExecuteNodeRequest) (*ExecuteNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteNode not implemented")
}
func (UnimplementedNodeExecutionServiceServer) mustEmbedUnimplementedNodeExecutionServiceServer() {}
func (UnimplementedNodeExecutionServiceServer) testEmbeddedByValue()                              {}

// UnsafeNodeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeExecutionServiceServer will
// result in compilation errors.
type UnsafeNodeExecutionServiceServer interface {
	mustEmbedUnimplementedNodeExecutionServiceServer()
}

func RegisterNodeExecutionServiceServer(s grpc.ServiceRegistrar, srv NodeExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeExecutionService_ServiceDesc, srv)
}

func _NodeExecutionService_ExecuteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeExecutionServiceServer).ExecuteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeExecutionService_ExecuteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeExecutionServiceServer).ExecuteNode(ctx, req.(*ExecuteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeExecutionService_ServiceDesc is the grpc.ServiceDesc for NodeExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rig.v1.NodeExecutionService",
	HandlerType: (*NodeExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteNode",
			Handler:    _NodeExecutionService_ExecuteNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/v1/node.proto",
}

const (
	ResourceService_ReadFile_FullMethodName    = "/rig.v1.ResourceService/ReadFile"
	ResourceService_WriteFile_FullMethodName   = "/rig.v1.ResourceService/WriteFile"
	ResourceService_ListDir_FullMethodName     = "/rig.v1.ResourceService/ListDir"
	ResourceService_HttpRequest_FullMethodName = "/rig.v1.ResourceService/HttpRequest"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ResourceService is implemented by the host to provide sandboxed access to resources.
// Plugins call back to this service over the established UDS connection.
type ResourceServiceClient interface {
	// ReadFile reads the contents of a file within the allowed workspace.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// WriteFile writes data to a file within the allowed workspace.
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// ListDir lists the contents of a directory within the allowed workspace.
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	// HttpRequest proxies an HTTP request if the node has network access.
	HttpRequest(ctx context.Context, in *HttpRequestRequest, opts ...grpc.CallOption) (*HttpRequestResponse, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, ResourceService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, ResourceService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, ResourceService_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) HttpRequest(ctx context.Context, in *HttpRequestRequest, opts ...grpc.CallOption) (*HttpRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpRequestResponse)
	err := c.cc.Invoke(ctx, ResourceService_HttpRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
//
// ResourceService is implemented by the host to provide sandboxed access to resources.
// Plugins call back to this service over the established UDS connection.
type ResourceServiceServer interface {
	// ReadFile reads the contents of a file within the allowed workspace.
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// WriteFile writes data to a file within the allowed workspace.
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// ListDir lists the contents of a directory within the allowed workspace.
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	// HttpRequest proxies an HTTP request if the node has network access.
	HttpRequest(context.Context, *HttpRequestRequest) (*HttpRequestResponse, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedResourceServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedResourceServiceServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedResourceServiceServer) HttpRequest(context.Context, *HttpRequestRequest) (*HttpRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HttpRequest not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_HttpRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).HttpRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_HttpRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).HttpRequest(ctx, req.(*HttpRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rig.v1.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _ResourceService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _ResourceService_WriteFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _ResourceService_ListDir_Handler,
		},
		{
			MethodName: "HttpRequest",
			Handler:    _ResourceService_HttpRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/v1/node.proto",
}
