// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/plugin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rig_version is the version of the Rig host.
	RigVersion    string `protobuf:"bytes,1,opt,name=rig_version,json=rigVersion,proto3" json:"rig_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetRigVersion() string {
	if x != nil {
		return x.RigVersion
	}
	return ""
}

type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plugin_version is the version of the plugin.
	PluginVersion string `protobuf:"bytes,1,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	// capabilities is a list of features the plugin supports.
	Capabilities  []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_pkg_api_v1_plugin_proto protoreflect.FileDescriptor

const file_pkg_api_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/v1/plugin.proto\x12\x06rig.v1\"3\n" +
	"\x10HandshakeRequest\x12\x1f\n" +
	"\vrig_version\x18\x01 \x01(\tR\n" +
	"rigVersion\"^\n" +
	"\x11HandshakeResponse\x12%\n" +
	"\x0eplugin_version\x18\x01 \x01(\tR\rpluginVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities2Q\n" +
	"\rPluginService\x12@\n" +
	"\tHandshake\x12\x18.rig.v1.HandshakeRequest\x1a\x19.rig.v1.HandshakeResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_plugin_proto_rawDescOnce sync.Once
	file_pkg_api_v1_plugin_proto_rawDescData []byte
)

func file_pkg_api_v1_plugin_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_plugin_proto_rawDesc), len(file_pkg_api_v1_plugin_proto_rawDesc)))
	})
	return file_pkg_api_v1_plugin_proto_rawDescData
}

var file_pkg_api_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_v1_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),  // 0: rig.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 1: rig.v1.HandshakeResponse
}
var file_pkg_api_v1_plugin_proto_depIdxs = []int32{
	0, // 0: rig.v1.PluginService.Handshake:input_type -> rig.v1.HandshakeRequest
	1, // 1: rig.v1.PluginService.Handshake:output_type -> rig.v1.HandshakeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_plugin_proto_init() }
func file_pkg_api_v1_plugin_proto_init() {
	if File_pkg_api_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_plugin_proto_rawDesc), len(file_pkg_api_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_plugin_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_plugin_proto = out.File
	file_pkg_api_v1_plugin_proto_goTypes = nil
	file_pkg_api_v1_plugin_proto_depIdxs = nil
}
