// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/plugin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rig_version is the version of the Rig host.
	// Deprecated: Use api_version (tag 2) instead.
	//
	// Deprecated: Marked as deprecated in pkg/api/v1/plugin.proto.
	RigVersion string `protobuf:"bytes,1,opt,name=rig_version,json=rigVersion,proto3" json:"rig_version,omitempty"`
	// api_version is the version of the Plugin API supported by the Rig host.
	ApiVersion    string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in pkg/api/v1/plugin.proto.
func (x *HandshakeRequest) GetRigVersion() string {
	if x != nil {
		return x.RigVersion
	}
	return ""
}

func (x *HandshakeRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plugin_version is the legacy version field which previously mixed binary and API versions.
	// Deprecated: Use plugin_semver (tag 6) for the plugin binary's semantic version,
	// and api_version (tag 4) for the Plugin API contract version.
	//
	// Deprecated: Marked as deprecated in pkg/api/v1/plugin.proto.
	PluginVersion string `protobuf:"bytes,1,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	// capabilities_deprecated is the legacy capabilities field using simple strings.
	// Deprecated: Use capabilities (tag 5) for structured capability information.
	//
	// Deprecated: Marked as deprecated in pkg/api/v1/plugin.proto.
	CapabilitiesDeprecated []string `protobuf:"bytes,2,rep,name=capabilities_deprecated,json=capabilitiesDeprecated,proto3" json:"capabilities_deprecated,omitempty"`
	// plugin_id is the unique identifier for the plugin.
	PluginId string `protobuf:"bytes,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// api_version is the version of the Plugin API (contract) implemented by the plugin.
	ApiVersion string `protobuf:"bytes,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// capabilities is a list of features the plugin supports.
	Capabilities []*Capability `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// plugin_semver is the semantic version of the plugin binary itself.
	PluginSemver  string `protobuf:"bytes,6,opt,name=plugin_semver,json=pluginSemver,proto3" json:"plugin_semver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_plugin_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in pkg/api/v1/plugin.proto.
func (x *HandshakeResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

// Deprecated: Marked as deprecated in pkg/api/v1/plugin.proto.
func (x *HandshakeResponse) GetCapabilitiesDeprecated() []string {
	if x != nil {
		return x.CapabilitiesDeprecated
	}
	return nil
}

func (x *HandshakeResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HandshakeResponse) GetPluginSemver() string {
	if x != nil {
		return x.PluginSemver
	}
	return ""
}

// Capability represents a specific feature or integration point provided by a plugin.
type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique name of the capability (e.g., "git.worktree").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the version of the capability implementation.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pkg_api_v1_plugin_proto protoreflect.FileDescriptor

const file_pkg_api_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/v1/plugin.proto\x12\x06rig.v1\x1a\x1cpkg/api/v1/interaction.proto\"X\n" +
	"\x10HandshakeRequest\x12#\n" +
	"\vrig_version\x18\x01 \x01(\tB\x02\x18\x01R\n" +
	"rigVersion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\"\x96\x02\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x0eplugin_version\x18\x01 \x01(\tB\x02\x18\x01R\rpluginVersion\x12;\n" +
	"\x17capabilities_deprecated\x18\x02 \x03(\tB\x02\x18\x01R\x16capabilitiesDeprecated\x12\x1b\n" +
	"\tplugin_id\x18\x03 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\tR\n" +
	"apiVersion\x126\n" +
	"\fcapabilities\x18\x05 \x03(\v2\x12.rig.v1.CapabilityR\fcapabilities\x12#\n" +
	"\rplugin_semver\x18\x06 \x01(\tR\fpluginSemver\":\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x94\x01\n" +
	"\rPluginService\x12@\n" +
	"\tHandshake\x12\x18.rig.v1.HandshakeRequest\x1a\x19.rig.v1.HandshakeResponse\x12A\n" +
	"\bInteract\x12\x17.rig.v1.InteractRequest\x1a\x18.rig.v1.InteractResponse(\x010\x01B'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_plugin_proto_rawDescOnce sync.Once
	file_pkg_api_v1_plugin_proto_rawDescData []byte
)

func file_pkg_api_v1_plugin_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_plugin_proto_rawDesc), len(file_pkg_api_v1_plugin_proto_rawDesc)))
	})
	return file_pkg_api_v1_plugin_proto_rawDescData
}

var file_pkg_api_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_api_v1_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),  // 0: rig.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 1: rig.v1.HandshakeResponse
	(*Capability)(nil),        // 2: rig.v1.Capability
	(*InteractRequest)(nil),   // 3: rig.v1.InteractRequest
	(*InteractResponse)(nil),  // 4: rig.v1.InteractResponse
}
var file_pkg_api_v1_plugin_proto_depIdxs = []int32{
	2, // 0: rig.v1.HandshakeResponse.capabilities:type_name -> rig.v1.Capability
	0, // 1: rig.v1.PluginService.Handshake:input_type -> rig.v1.HandshakeRequest
	3, // 2: rig.v1.PluginService.Interact:input_type -> rig.v1.InteractRequest
	1, // 3: rig.v1.PluginService.Handshake:output_type -> rig.v1.HandshakeResponse
	4, // 4: rig.v1.PluginService.Interact:output_type -> rig.v1.InteractResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_plugin_proto_init() }
func file_pkg_api_v1_plugin_proto_init() {
	if File_pkg_api_v1_plugin_proto != nil {
		return
	}
	file_pkg_api_v1_interaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_plugin_proto_rawDesc), len(file_pkg_api_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_plugin_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_plugin_proto = out.File
	file_pkg_api_v1_plugin_proto_goTypes = nil
	file_pkg_api_v1_plugin_proto_depIdxs = nil
}
