// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/secret.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_pkg_api_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_pkg_api_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_secret_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pkg_api_v1_secret_proto protoreflect.FileDescriptor

const file_pkg_api_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/v1/secret.proto\x12\x06rig.v1\"$\n" +
	"\x10GetSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x11GetSecretResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2Q\n" +
	"\rSecretService\x12@\n" +
	"\tGetSecret\x12\x18.rig.v1.GetSecretRequest\x1a\x19.rig.v1.GetSecretResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_secret_proto_rawDescOnce sync.Once
	file_pkg_api_v1_secret_proto_rawDescData []byte
)

func file_pkg_api_v1_secret_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_secret_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_secret_proto_rawDesc), len(file_pkg_api_v1_secret_proto_rawDesc)))
	})
	return file_pkg_api_v1_secret_proto_rawDescData
}

var file_pkg_api_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_v1_secret_proto_goTypes = []any{
	(*GetSecretRequest)(nil),  // 0: rig.v1.GetSecretRequest
	(*GetSecretResponse)(nil), // 1: rig.v1.GetSecretResponse
}
var file_pkg_api_v1_secret_proto_depIdxs = []int32{
	0, // 0: rig.v1.SecretService.GetSecret:input_type -> rig.v1.GetSecretRequest
	1, // 1: rig.v1.SecretService.GetSecret:output_type -> rig.v1.GetSecretResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_secret_proto_init() }
func file_pkg_api_v1_secret_proto_init() {
	if File_pkg_api_v1_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_secret_proto_rawDesc), len(file_pkg_api_v1_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_secret_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_secret_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_secret_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_secret_proto = out.File
	file_pkg_api_v1_secret_proto_goTypes = nil
	file_pkg_api_v1_secret_proto_depIdxs = nil
}
