// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/telemetry.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity defines the logging levels for telemetry events.
// These align with Go's standard log/slog levels.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_DEBUG       Severity = 1
	Severity_SEVERITY_INFO        Severity = 2
	Severity_SEVERITY_WARN        Severity = 3
	Severity_SEVERITY_ERROR       Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_DEBUG",
		2: "SEVERITY_INFO",
		3: "SEVERITY_WARN",
		4: "SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_DEBUG":       1,
		"SEVERITY_INFO":        2,
		"SEVERITY_WARN":        3,
		"SEVERITY_ERROR":       4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_telemetry_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// ErrorDomain identifies the subsystem where an error originated.
// This mirrors the domain error types in pkg/errors/types.go.
type ErrorDomain int32

const (
	ErrorDomain_ERROR_DOMAIN_UNSPECIFIED ErrorDomain = 0
	ErrorDomain_ERROR_DOMAIN_CONFIG      ErrorDomain = 1
	ErrorDomain_ERROR_DOMAIN_GITHUB      ErrorDomain = 2
	ErrorDomain_ERROR_DOMAIN_AI          ErrorDomain = 3
	ErrorDomain_ERROR_DOMAIN_JIRA        ErrorDomain = 4
	ErrorDomain_ERROR_DOMAIN_BEADS       ErrorDomain = 5
	ErrorDomain_ERROR_DOMAIN_WORKFLOW    ErrorDomain = 6
	ErrorDomain_ERROR_DOMAIN_CAPABILITY  ErrorDomain = 7
	ErrorDomain_ERROR_DOMAIN_PLUGIN      ErrorDomain = 8
	ErrorDomain_ERROR_DOMAIN_DAEMON      ErrorDomain = 9
	ErrorDomain_ERROR_DOMAIN_DATABASE    ErrorDomain = 10
)

// Enum value maps for ErrorDomain.
var (
	ErrorDomain_name = map[int32]string{
		0:  "ERROR_DOMAIN_UNSPECIFIED",
		1:  "ERROR_DOMAIN_CONFIG",
		2:  "ERROR_DOMAIN_GITHUB",
		3:  "ERROR_DOMAIN_AI",
		4:  "ERROR_DOMAIN_JIRA",
		5:  "ERROR_DOMAIN_BEADS",
		6:  "ERROR_DOMAIN_WORKFLOW",
		7:  "ERROR_DOMAIN_CAPABILITY",
		8:  "ERROR_DOMAIN_PLUGIN",
		9:  "ERROR_DOMAIN_DAEMON",
		10: "ERROR_DOMAIN_DATABASE",
	}
	ErrorDomain_value = map[string]int32{
		"ERROR_DOMAIN_UNSPECIFIED": 0,
		"ERROR_DOMAIN_CONFIG":      1,
		"ERROR_DOMAIN_GITHUB":      2,
		"ERROR_DOMAIN_AI":          3,
		"ERROR_DOMAIN_JIRA":        4,
		"ERROR_DOMAIN_BEADS":       5,
		"ERROR_DOMAIN_WORKFLOW":    6,
		"ERROR_DOMAIN_CAPABILITY":  7,
		"ERROR_DOMAIN_PLUGIN":      8,
		"ERROR_DOMAIN_DAEMON":      9,
		"ERROR_DOMAIN_DATABASE":    10,
	}
)

func (x ErrorDomain) Enum() *ErrorDomain {
	p := new(ErrorDomain)
	*p = x
	return p
}

func (x ErrorDomain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorDomain) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_telemetry_proto_enumTypes[1].Descriptor()
}

func (ErrorDomain) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_telemetry_proto_enumTypes[1]
}

func (x ErrorDomain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorDomain.Descriptor instead.
func (ErrorDomain) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

// LogEntry represents a single structured log message emitted by a component.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// severity is the importance level of the log message.
	Severity Severity `protobuf:"varint,1,opt,name=severity,proto3,enum=rig.v1.Severity" json:"severity,omitempty"`
	// timestamp is when the log event occurred in UTC.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// message is the human-readable description of the event.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// context contains arbitrary structured metadata associated with the log.
	// Sensitive data in context must be redacted before transmission to the host.
	Context *structpb.Struct `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	// source identifies the component or plugin that emitted the log.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// correlation_id ties this log to a specific workflow or process for tracing.
	// Matches pkg/events.WorkflowEvent.CorrelationID.
	CorrelationId string `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// ErrorReport provides rich, domain-specific error details for cross-process troubleshooting.
// It extends the basic gRPC status model with Rig-specific error fields.
type ErrorReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// domain is the subsystem that encountered the error.
	Domain ErrorDomain `protobuf:"varint,1,opt,name=domain,proto3,enum=rig.v1.ErrorDomain" json:"domain,omitempty"`
	// operation describes what the component was doing when it failed (e.g., "CreateWorktree").
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// message is a developer-facing description of the error.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// status_code is an optional numeric error code (e.g., HTTP or gRPC status).
	StatusCode int32 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// retryable indicates if the failure is transient and can be retried by the caller.
	Retryable bool `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// metadata contains machine-readable structured details about the error.
	Metadata *structpb.Struct `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// correlation_id ties this error to a specific workflow event for tracing.
	CorrelationId string `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// severity indicates the impact of the error (WARN for degraded, ERROR for fatal).
	Severity      Severity `protobuf:"varint,8,opt,name=severity,proto3,enum=rig.v1.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReport) Reset() {
	*x = ErrorReport{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReport) ProtoMessage() {}

func (x *ErrorReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReport.ProtoReflect.Descriptor instead.
func (*ErrorReport) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorReport) GetDomain() ErrorDomain {
	if x != nil {
		return x.Domain
	}
	return ErrorDomain_ERROR_DOMAIN_UNSPECIFIED
}

func (x *ErrorReport) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ErrorReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorReport) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ErrorReport) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorReport) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ErrorReport) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ErrorReport) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

// TelemetryBatch allows for efficient aggregation and transmission of multiple telemetry events.
type TelemetryBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log_entries is a collection of log messages.
	LogEntries []*LogEntry `protobuf:"bytes,1,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	// error_reports is a collection of structured error reports.
	ErrorReports  []*ErrorReport `protobuf:"bytes,2,rep,name=error_reports,json=errorReports,proto3" json:"error_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryBatch) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

func (x *TelemetryBatch) GetErrorReports() []*ErrorReport {
	if x != nil {
		return x.ErrorReports
	}
	return nil
}

// ReportEventRequest wraps a single telemetry event for transmission.
type ReportEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the session-scoped authentication token provided by the host.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// entry is the log message to report.
	Entry *LogEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	// error is the error report to report.
	Error         *ErrorReport `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventRequest) Reset() {
	*x = ReportEventRequest{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventRequest) ProtoMessage() {}

func (x *ReportEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventRequest.ProtoReflect.Descriptor instead.
func (*ReportEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *ReportEventRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReportEventRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *ReportEventRequest) GetError() *ErrorReport {
	if x != nil {
		return x.Error
	}
	return nil
}

// ReportEventResponse is the acknowledgement of a successful event report.
type ReportEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventResponse) Reset() {
	*x = ReportEventResponse{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventResponse) ProtoMessage() {}

func (x *ReportEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventResponse.ProtoReflect.Descriptor instead.
func (*ReportEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

// StreamEventsRequest wraps telemetry events for streaming transmission.
type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the session-scoped authentication token.
	// Only required on the first message of the stream.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// entry is an individual log message.
	Entry *LogEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	// error is an individual error report.
	Error         *ErrorReport `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *StreamEventsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StreamEventsRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StreamEventsRequest) GetError() *ErrorReport {
	if x != nil {
		return x.Error
	}
	return nil
}

// StreamEventsResponse is sent by the host periodically or upon stream completion.
type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

// BatchEventsRequest wraps a batch of telemetry events.
type BatchEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the session-scoped authentication token.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// batch contains multiple telemetry events.
	Batch         *TelemetryBatch `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEventsRequest) Reset() {
	*x = BatchEventsRequest{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEventsRequest) ProtoMessage() {}

func (x *BatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEventsRequest.ProtoReflect.Descriptor instead.
func (*BatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *BatchEventsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BatchEventsRequest) GetBatch() *TelemetryBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

// BatchEventsResponse acknowledges receipt of a telemetry batch.
type BatchEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEventsResponse) Reset() {
	*x = BatchEventsResponse{}
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEventsResponse) ProtoMessage() {}

func (x *BatchEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEventsResponse.ProtoReflect.Descriptor instead.
func (*BatchEventsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

var File_pkg_api_v1_telemetry_proto protoreflect.FileDescriptor

const file_pkg_api_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/api/v1/telemetry.proto\x12\x06rig.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x01\n" +
	"\bLogEntry\x12,\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x10.rig.v1.SeverityR\bseverity\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\"\xbb\x02\n" +
	"\vErrorReport\x12+\n" +
	"\x06domain\x18\x01 \x01(\x0e2\x13.rig.v1.ErrorDomainR\x06domain\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\x12,\n" +
	"\bseverity\x18\b \x01(\x0e2\x10.rig.v1.SeverityR\bseverity\"}\n" +
	"\x0eTelemetryBatch\x121\n" +
	"\vlog_entries\x18\x01 \x03(\v2\x10.rig.v1.LogEntryR\n" +
	"logEntries\x128\n" +
	"\rerror_reports\x18\x02 \x03(\v2\x13.rig.v1.ErrorReportR\ferrorReports\"}\n" +
	"\x12ReportEventRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x05entry\x18\x02 \x01(\v2\x10.rig.v1.LogEntryR\x05entry\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.rig.v1.ErrorReportR\x05error\"\x15\n" +
	"\x13ReportEventResponse\"~\n" +
	"\x13StreamEventsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x05entry\x18\x02 \x01(\v2\x10.rig.v1.LogEntryR\x05entry\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.rig.v1.ErrorReportR\x05error\"\x16\n" +
	"\x14StreamEventsResponse\"X\n" +
	"\x12BatchEventsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12,\n" +
	"\x05batch\x18\x02 \x01(\v2\x16.rig.v1.TelemetryBatchR\x05batch\"\x15\n" +
	"\x13BatchEventsResponse*r\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_DEBUG\x10\x01\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x02\x12\x11\n" +
	"\rSEVERITY_WARN\x10\x03\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x04*\xa6\x02\n" +
	"\vErrorDomain\x12\x1c\n" +
	"\x18ERROR_DOMAIN_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ERROR_DOMAIN_CONFIG\x10\x01\x12\x17\n" +
	"\x13ERROR_DOMAIN_GITHUB\x10\x02\x12\x13\n" +
	"\x0fERROR_DOMAIN_AI\x10\x03\x12\x15\n" +
	"\x11ERROR_DOMAIN_JIRA\x10\x04\x12\x16\n" +
	"\x12ERROR_DOMAIN_BEADS\x10\x05\x12\x19\n" +
	"\x15ERROR_DOMAIN_WORKFLOW\x10\x06\x12\x1b\n" +
	"\x17ERROR_DOMAIN_CAPABILITY\x10\a\x12\x17\n" +
	"\x13ERROR_DOMAIN_PLUGIN\x10\b\x12\x17\n" +
	"\x13ERROR_DOMAIN_DAEMON\x10\t\x12\x19\n" +
	"\x15ERROR_DOMAIN_DATABASE\x10\n" +
	"2\xef\x01\n" +
	"\x10TelemetryService\x12F\n" +
	"\vReportEvent\x12\x1a.rig.v1.ReportEventRequest\x1a\x1b.rig.v1.ReportEventResponse\x12K\n" +
	"\fStreamEvents\x12\x1b.rig.v1.StreamEventsRequest\x1a\x1c.rig.v1.StreamEventsResponse(\x01\x12F\n" +
	"\vBatchEvents\x12\x1a.rig.v1.BatchEventsRequest\x1a\x1b.rig.v1.BatchEventsResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_telemetry_proto_rawDescOnce sync.Once
	file_pkg_api_v1_telemetry_proto_rawDescData []byte
)

func file_pkg_api_v1_telemetry_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_telemetry_proto_rawDesc), len(file_pkg_api_v1_telemetry_proto_rawDesc)))
	})
	return file_pkg_api_v1_telemetry_proto_rawDescData
}

var file_pkg_api_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_api_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_v1_telemetry_proto_goTypes = []any{
	(Severity)(0),                 // 0: rig.v1.Severity
	(ErrorDomain)(0),              // 1: rig.v1.ErrorDomain
	(*LogEntry)(nil),              // 2: rig.v1.LogEntry
	(*ErrorReport)(nil),           // 3: rig.v1.ErrorReport
	(*TelemetryBatch)(nil),        // 4: rig.v1.TelemetryBatch
	(*ReportEventRequest)(nil),    // 5: rig.v1.ReportEventRequest
	(*ReportEventResponse)(nil),   // 6: rig.v1.ReportEventResponse
	(*StreamEventsRequest)(nil),   // 7: rig.v1.StreamEventsRequest
	(*StreamEventsResponse)(nil),  // 8: rig.v1.StreamEventsResponse
	(*BatchEventsRequest)(nil),    // 9: rig.v1.BatchEventsRequest
	(*BatchEventsResponse)(nil),   // 10: rig.v1.BatchEventsResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 12: google.protobuf.Struct
}
var file_pkg_api_v1_telemetry_proto_depIdxs = []int32{
	0,  // 0: rig.v1.LogEntry.severity:type_name -> rig.v1.Severity
	11, // 1: rig.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	12, // 2: rig.v1.LogEntry.context:type_name -> google.protobuf.Struct
	1,  // 3: rig.v1.ErrorReport.domain:type_name -> rig.v1.ErrorDomain
	12, // 4: rig.v1.ErrorReport.metadata:type_name -> google.protobuf.Struct
	0,  // 5: rig.v1.ErrorReport.severity:type_name -> rig.v1.Severity
	2,  // 6: rig.v1.TelemetryBatch.log_entries:type_name -> rig.v1.LogEntry
	3,  // 7: rig.v1.TelemetryBatch.error_reports:type_name -> rig.v1.ErrorReport
	2,  // 8: rig.v1.ReportEventRequest.entry:type_name -> rig.v1.LogEntry
	3,  // 9: rig.v1.ReportEventRequest.error:type_name -> rig.v1.ErrorReport
	2,  // 10: rig.v1.StreamEventsRequest.entry:type_name -> rig.v1.LogEntry
	3,  // 11: rig.v1.StreamEventsRequest.error:type_name -> rig.v1.ErrorReport
	4,  // 12: rig.v1.BatchEventsRequest.batch:type_name -> rig.v1.TelemetryBatch
	5,  // 13: rig.v1.TelemetryService.ReportEvent:input_type -> rig.v1.ReportEventRequest
	7,  // 14: rig.v1.TelemetryService.StreamEvents:input_type -> rig.v1.StreamEventsRequest
	9,  // 15: rig.v1.TelemetryService.BatchEvents:input_type -> rig.v1.BatchEventsRequest
	6,  // 16: rig.v1.TelemetryService.ReportEvent:output_type -> rig.v1.ReportEventResponse
	8,  // 17: rig.v1.TelemetryService.StreamEvents:output_type -> rig.v1.StreamEventsResponse
	10, // 18: rig.v1.TelemetryService.BatchEvents:output_type -> rig.v1.BatchEventsResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_telemetry_proto_init() }
func file_pkg_api_v1_telemetry_proto_init() {
	if File_pkg_api_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_telemetry_proto_rawDesc), len(file_pkg_api_v1_telemetry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_pkg_api_v1_telemetry_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_telemetry_proto = out.File
	file_pkg_api_v1_telemetry_proto_goTypes = nil
	file_pkg_api_v1_telemetry_proto_depIdxs = nil
}
