// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/ticket.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTicketInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketInfoRequest) Reset() {
	*x = GetTicketInfoRequest{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketInfoRequest) ProtoMessage() {}

func (x *GetTicketInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTicketInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *GetTicketInfoRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type TicketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CustomFields  map[string]string      `protobuf:"bytes,6,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketInfo) Reset() {
	*x = TicketInfo{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketInfo) ProtoMessage() {}

func (x *TicketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketInfo.ProtoReflect.Descriptor instead.
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *TicketInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TicketInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketInfo) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *TicketInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TicketInfo) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

func (x *TicketInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetTicketInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *TicketInfo            `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketInfoResponse) Reset() {
	*x = GetTicketInfoResponse{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketInfoResponse) ProtoMessage() {}

func (x *GetTicketInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTicketInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *GetTicketInfoResponse) GetTicket() *TicketInfo {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type UpdateTicketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketStatusRequest) Reset() {
	*x = UpdateTicketStatusRequest{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketStatusRequest) ProtoMessage() {}

func (x *UpdateTicketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTicketStatusRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *UpdateTicketStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateTicketStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketStatusResponse) Reset() {
	*x = UpdateTicketStatusResponse{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketStatusResponse) ProtoMessage() {}

func (x *UpdateTicketStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTicketStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTicketStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Transition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *Transition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTransitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransitionsRequest) Reset() {
	*x = ListTransitionsRequest{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransitionsRequest) ProtoMessage() {}

func (x *ListTransitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransitionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransitionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransitionsRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type ListTransitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transitions   []*Transition          `protobuf:"bytes,1,rep,name=transitions,proto3" json:"transitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransitionsResponse) Reset() {
	*x = ListTransitionsResponse{}
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransitionsResponse) ProtoMessage() {}

func (x *ListTransitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransitionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransitionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *ListTransitionsResponse) GetTransitions() []*Transition {
	if x != nil {
		return x.Transitions
	}
	return nil
}

var File_pkg_api_v1_ticket_proto protoreflect.FileDescriptor

const file_pkg_api_v1_ticket_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/v1/ticket.proto\x12\x06rig.v1\"3\n" +
	"\x14GetTicketInfoRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"\xa8\x02\n" +
	"\n" +
	"TicketInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12I\n" +
	"\rcustom_fields\x18\x06 \x03(\v2$.rig.v1.TicketInfo.CustomFieldsEntryR\fcustomFields\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x15GetTicketInfoResponse\x12*\n" +
	"\x06ticket\x18\x01 \x01(\v2\x12.rig.v1.TicketInfoR\x06ticket\"P\n" +
	"\x19UpdateTicketStatusRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"6\n" +
	"\x1aUpdateTicketStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\n" +
	"Transition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x16ListTransitionsRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"O\n" +
	"\x17ListTransitionsResponse\x124\n" +
	"\vtransitions\x18\x01 \x03(\v2\x12.rig.v1.TransitionR\vtransitions2\x8e\x02\n" +
	"\rTicketService\x12L\n" +
	"\rGetTicketInfo\x12\x1c.rig.v1.GetTicketInfoRequest\x1a\x1d.rig.v1.GetTicketInfoResponse\x12[\n" +
	"\x12UpdateTicketStatus\x12!.rig.v1.UpdateTicketStatusRequest\x1a\".rig.v1.UpdateTicketStatusResponse\x12R\n" +
	"\x0fListTransitions\x12\x1e.rig.v1.ListTransitionsRequest\x1a\x1f.rig.v1.ListTransitionsResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_ticket_proto_rawDescOnce sync.Once
	file_pkg_api_v1_ticket_proto_rawDescData []byte
)

func file_pkg_api_v1_ticket_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_ticket_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_ticket_proto_rawDesc), len(file_pkg_api_v1_ticket_proto_rawDesc)))
	})
	return file_pkg_api_v1_ticket_proto_rawDescData
}

var file_pkg_api_v1_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_v1_ticket_proto_goTypes = []any{
	(*GetTicketInfoRequest)(nil),       // 0: rig.v1.GetTicketInfoRequest
	(*TicketInfo)(nil),                 // 1: rig.v1.TicketInfo
	(*GetTicketInfoResponse)(nil),      // 2: rig.v1.GetTicketInfoResponse
	(*UpdateTicketStatusRequest)(nil),  // 3: rig.v1.UpdateTicketStatusRequest
	(*UpdateTicketStatusResponse)(nil), // 4: rig.v1.UpdateTicketStatusResponse
	(*Transition)(nil),                 // 5: rig.v1.Transition
	(*ListTransitionsRequest)(nil),     // 6: rig.v1.ListTransitionsRequest
	(*ListTransitionsResponse)(nil),    // 7: rig.v1.ListTransitionsResponse
	nil,                                // 8: rig.v1.TicketInfo.CustomFieldsEntry
}
var file_pkg_api_v1_ticket_proto_depIdxs = []int32{
	8, // 0: rig.v1.TicketInfo.custom_fields:type_name -> rig.v1.TicketInfo.CustomFieldsEntry
	1, // 1: rig.v1.GetTicketInfoResponse.ticket:type_name -> rig.v1.TicketInfo
	5, // 2: rig.v1.ListTransitionsResponse.transitions:type_name -> rig.v1.Transition
	0, // 3: rig.v1.TicketService.GetTicketInfo:input_type -> rig.v1.GetTicketInfoRequest
	3, // 4: rig.v1.TicketService.UpdateTicketStatus:input_type -> rig.v1.UpdateTicketStatusRequest
	6, // 5: rig.v1.TicketService.ListTransitions:input_type -> rig.v1.ListTransitionsRequest
	2, // 6: rig.v1.TicketService.GetTicketInfo:output_type -> rig.v1.GetTicketInfoResponse
	4, // 7: rig.v1.TicketService.UpdateTicketStatus:output_type -> rig.v1.UpdateTicketStatusResponse
	7, // 8: rig.v1.TicketService.ListTransitions:output_type -> rig.v1.ListTransitionsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_ticket_proto_init() }
func file_pkg_api_v1_ticket_proto_init() {
	if File_pkg_api_v1_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_ticket_proto_rawDesc), len(file_pkg_api_v1_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_ticket_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_ticket_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_ticket_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_ticket_proto = out.File
	file_pkg_api_v1_ticket_proto_goTypes = nil
	file_pkg_api_v1_ticket_proto_depIdxs = nil
}
