// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/v1/vcs.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepoRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoRootRequest) Reset() {
	*x = GetRepoRootRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoRootRequest) ProtoMessage() {}

func (x *GetRepoRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoRootRequest.ProtoReflect.Descriptor instead.
func (*GetRepoRootRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepoRootRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetRepoRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoRootResponse) Reset() {
	*x = GetRepoRootResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoRootResponse) ProtoMessage() {}

func (x *GetRepoRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoRootResponse.ProtoReflect.Descriptor instead.
func (*GetRepoRootResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepoRootResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type GetRepoNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoNameRequest) Reset() {
	*x = GetRepoNameRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoNameRequest) ProtoMessage() {}

func (x *GetRepoNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoNameRequest.ProtoReflect.Descriptor instead.
func (*GetRepoNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{2}
}

func (x *GetRepoNameRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetRepoNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoNameResponse) Reset() {
	*x = GetRepoNameResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoNameResponse) ProtoMessage() {}

func (x *GetRepoNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoNameResponse.ProtoReflect.Descriptor instead.
func (*GetRepoNameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{3}
}

func (x *GetRepoNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDefaultBranchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BaseBranchConfig string                 `protobuf:"bytes,2,opt,name=base_branch_config,json=baseBranchConfig,proto3" json:"base_branch_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDefaultBranchRequest) Reset() {
	*x = GetDefaultBranchRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultBranchRequest) ProtoMessage() {}

func (x *GetDefaultBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultBranchRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultBranchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{4}
}

func (x *GetDefaultBranchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDefaultBranchRequest) GetBaseBranchConfig() string {
	if x != nil {
		return x.BaseBranchConfig
	}
	return ""
}

type GetDefaultBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultBranchResponse) Reset() {
	*x = GetDefaultBranchResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultBranchResponse) ProtoMessage() {}

func (x *GetDefaultBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultBranchResponse.ProtoReflect.Descriptor instead.
func (*GetDefaultBranchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{5}
}

func (x *GetDefaultBranchResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type CreateWorktreeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TicketType       string                 `protobuf:"bytes,2,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BranchName       string                 `protobuf:"bytes,4,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	BaseBranchConfig string                 `protobuf:"bytes,5,opt,name=base_branch_config,json=baseBranchConfig,proto3" json:"base_branch_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateWorktreeRequest) Reset() {
	*x = CreateWorktreeRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorktreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorktreeRequest) ProtoMessage() {}

func (x *CreateWorktreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorktreeRequest.ProtoReflect.Descriptor instead.
func (*CreateWorktreeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorktreeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateWorktreeRequest) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *CreateWorktreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorktreeRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *CreateWorktreeRequest) GetBaseBranchConfig() string {
	if x != nil {
		return x.BaseBranchConfig
	}
	return ""
}

type CreateWorktreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorktreePath  string                 `protobuf:"bytes,1,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorktreeResponse) Reset() {
	*x = CreateWorktreeResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorktreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorktreeResponse) ProtoMessage() {}

func (x *CreateWorktreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorktreeResponse.ProtoReflect.Descriptor instead.
func (*CreateWorktreeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWorktreeResponse) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

type ListWorktreesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesRequest) Reset() {
	*x = ListWorktreesRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesRequest) ProtoMessage() {}

func (x *ListWorktreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesRequest.ProtoReflect.Descriptor instead.
func (*ListWorktreesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorktreesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type WorktreeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorktreeInfo) Reset() {
	*x = WorktreeInfo{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorktreeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorktreeInfo) ProtoMessage() {}

func (x *WorktreeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorktreeInfo.ProtoReflect.Descriptor instead.
func (*WorktreeInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{9}
}

func (x *WorktreeInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorktreeInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type ListWorktreesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worktrees     []*WorktreeInfo        `protobuf:"bytes,1,rep,name=worktrees,proto3" json:"worktrees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesResponse) Reset() {
	*x = ListWorktreesResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesResponse) ProtoMessage() {}

func (x *ListWorktreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesResponse.ProtoReflect.Descriptor instead.
func (*ListWorktreesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorktreesResponse) GetWorktrees() []*WorktreeInfo {
	if x != nil {
		return x.Worktrees
	}
	return nil
}

type RemoveWorktreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TicketType    string                 `protobuf:"bytes,2,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	Ticket        string                 `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorktreeRequest) Reset() {
	*x = RemoveWorktreeRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorktreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorktreeRequest) ProtoMessage() {}

func (x *RemoveWorktreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorktreeRequest.ProtoReflect.Descriptor instead.
func (*RemoveWorktreeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveWorktreeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveWorktreeRequest) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *RemoveWorktreeRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type RemoveWorktreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorktreeResponse) Reset() {
	*x = RemoveWorktreeResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorktreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorktreeResponse) ProtoMessage() {}

func (x *RemoveWorktreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorktreeResponse.ProtoReflect.Descriptor instead.
func (*RemoveWorktreeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{12}
}

type ForceRemoveWorktreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,2,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceRemoveWorktreeRequest) Reset() {
	*x = ForceRemoveWorktreeRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceRemoveWorktreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceRemoveWorktreeRequest) ProtoMessage() {}

func (x *ForceRemoveWorktreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceRemoveWorktreeRequest.ProtoReflect.Descriptor instead.
func (*ForceRemoveWorktreeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{13}
}

func (x *ForceRemoveWorktreeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ForceRemoveWorktreeRequest) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

type ForceRemoveWorktreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceRemoveWorktreeResponse) Reset() {
	*x = ForceRemoveWorktreeResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceRemoveWorktreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceRemoveWorktreeResponse) ProtoMessage() {}

func (x *ForceRemoveWorktreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceRemoveWorktreeResponse.ProtoReflect.Descriptor instead.
func (*ForceRemoveWorktreeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{14}
}

type GetWorktreePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TicketType    string                 `protobuf:"bytes,2,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	Ticket        string                 `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorktreePathRequest) Reset() {
	*x = GetWorktreePathRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorktreePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorktreePathRequest) ProtoMessage() {}

func (x *GetWorktreePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorktreePathRequest.ProtoReflect.Descriptor instead.
func (*GetWorktreePathRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{15}
}

func (x *GetWorktreePathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetWorktreePathRequest) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *GetWorktreePathRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type GetWorktreePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorktreePath  string                 `protobuf:"bytes,1,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorktreePathResponse) Reset() {
	*x = GetWorktreePathResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorktreePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorktreePathResponse) ProtoMessage() {}

func (x *GetWorktreePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorktreePathResponse.ProtoReflect.Descriptor instead.
func (*GetWorktreePathResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{16}
}

func (x *GetWorktreePathResponse) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

type CloneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	BasePath      string                 `protobuf:"bytes,2,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{17}
}

func (x *CloneRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CloneRequest) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

type CloneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{18}
}

func (x *CloneResponse) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

type IsBranchMergedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	BaseBranch    string                 `protobuf:"bytes,3,opt,name=base_branch,json=baseBranch,proto3" json:"base_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBranchMergedRequest) Reset() {
	*x = IsBranchMergedRequest{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBranchMergedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBranchMergedRequest) ProtoMessage() {}

func (x *IsBranchMergedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBranchMergedRequest.ProtoReflect.Descriptor instead.
func (*IsBranchMergedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{19}
}

func (x *IsBranchMergedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IsBranchMergedRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *IsBranchMergedRequest) GetBaseBranch() string {
	if x != nil {
		return x.BaseBranch
	}
	return ""
}

type IsBranchMergedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMerged      bool                   `protobuf:"varint,1,opt,name=is_merged,json=isMerged,proto3" json:"is_merged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBranchMergedResponse) Reset() {
	*x = IsBranchMergedResponse{}
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBranchMergedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBranchMergedResponse) ProtoMessage() {}

func (x *IsBranchMergedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_vcs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBranchMergedResponse.ProtoReflect.Descriptor instead.
func (*IsBranchMergedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_vcs_proto_rawDescGZIP(), []int{20}
}

func (x *IsBranchMergedResponse) GetIsMerged() bool {
	if x != nil {
		return x.IsMerged
	}
	return false
}

var File_pkg_api_v1_vcs_proto protoreflect.FileDescriptor

const file_pkg_api_v1_vcs_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/api/v1/vcs.proto\x12\x06rig.v1\"(\n" +
	"\x12GetRepoRootRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\")\n" +
	"\x13GetRepoRootResponse\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\"(\n" +
	"\x12GetRepoNameRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\")\n" +
	"\x13GetRepoNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"[\n" +
	"\x17GetDefaultBranchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12,\n" +
	"\x12base_branch_config\x18\x02 \x01(\tR\x10baseBranchConfig\"2\n" +
	"\x18GetDefaultBranchResponse\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\"\xaf\x01\n" +
	"\x15CreateWorktreeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vticket_type\x18\x02 \x01(\tR\n" +
	"ticketType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vbranch_name\x18\x04 \x01(\tR\n" +
	"branchName\x12,\n" +
	"\x12base_branch_config\x18\x05 \x01(\tR\x10baseBranchConfig\"=\n" +
	"\x16CreateWorktreeResponse\x12#\n" +
	"\rworktree_path\x18\x01 \x01(\tR\fworktreePath\"*\n" +
	"\x14ListWorktreesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\":\n" +
	"\fWorktreeInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"K\n" +
	"\x15ListWorktreesResponse\x122\n" +
	"\tworktrees\x18\x01 \x03(\v2\x14.rig.v1.WorktreeInfoR\tworktrees\"d\n" +
	"\x15RemoveWorktreeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vticket_type\x18\x02 \x01(\tR\n" +
	"ticketType\x12\x16\n" +
	"\x06ticket\x18\x03 \x01(\tR\x06ticket\"\x18\n" +
	"\x16RemoveWorktreeResponse\"U\n" +
	"\x1aForceRemoveWorktreeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rworktree_path\x18\x02 \x01(\tR\fworktreePath\"\x1d\n" +
	"\x1bForceRemoveWorktreeResponse\"e\n" +
	"\x16GetWorktreePathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vticket_type\x18\x02 \x01(\tR\n" +
	"ticketType\x12\x16\n" +
	"\x06ticket\x18\x03 \x01(\tR\x06ticket\">\n" +
	"\x17GetWorktreePathResponse\x12#\n" +
	"\rworktree_path\x18\x01 \x01(\tR\fworktreePath\"=\n" +
	"\fCloneRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tbase_path\x18\x02 \x01(\tR\bbasePath\",\n" +
	"\rCloneResponse\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\"d\n" +
	"\x15IsBranchMergedRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1f\n" +
	"\vbase_branch\x18\x03 \x01(\tR\n" +
	"baseBranch\"5\n" +
	"\x16IsBranchMergedResponse\x12\x1b\n" +
	"\tis_merged\x18\x01 \x01(\bR\bisMerged2\x9e\x06\n" +
	"\n" +
	"VCSService\x12F\n" +
	"\vGetRepoRoot\x12\x1a.rig.v1.GetRepoRootRequest\x1a\x1b.rig.v1.GetRepoRootResponse\x12F\n" +
	"\vGetRepoName\x12\x1a.rig.v1.GetRepoNameRequest\x1a\x1b.rig.v1.GetRepoNameResponse\x12U\n" +
	"\x10GetDefaultBranch\x12\x1f.rig.v1.GetDefaultBranchRequest\x1a .rig.v1.GetDefaultBranchResponse\x12O\n" +
	"\x0eCreateWorktree\x12\x1d.rig.v1.CreateWorktreeRequest\x1a\x1e.rig.v1.CreateWorktreeResponse\x12L\n" +
	"\rListWorktrees\x12\x1c.rig.v1.ListWorktreesRequest\x1a\x1d.rig.v1.ListWorktreesResponse\x12O\n" +
	"\x0eRemoveWorktree\x12\x1d.rig.v1.RemoveWorktreeRequest\x1a\x1e.rig.v1.RemoveWorktreeResponse\x12^\n" +
	"\x13ForceRemoveWorktree\x12\".rig.v1.ForceRemoveWorktreeRequest\x1a#.rig.v1.ForceRemoveWorktreeResponse\x12R\n" +
	"\x0fGetWorktreePath\x12\x1e.rig.v1.GetWorktreePathRequest\x1a\x1f.rig.v1.GetWorktreePathResponse\x124\n" +
	"\x05Clone\x12\x14.rig.v1.CloneRequest\x1a\x15.rig.v1.CloneResponse\x12O\n" +
	"\x0eIsBranchMerged\x12\x1d.rig.v1.IsBranchMergedRequest\x1a\x1e.rig.v1.IsBranchMergedResponseB'Z%thoreinstein.com/rig/pkg/api/v1;apiv1b\x06proto3"

var (
	file_pkg_api_v1_vcs_proto_rawDescOnce sync.Once
	file_pkg_api_v1_vcs_proto_rawDescData []byte
)

func file_pkg_api_v1_vcs_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_vcs_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_vcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_vcs_proto_rawDesc), len(file_pkg_api_v1_vcs_proto_rawDesc)))
	})
	return file_pkg_api_v1_vcs_proto_rawDescData
}

var file_pkg_api_v1_vcs_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_api_v1_vcs_proto_goTypes = []any{
	(*GetRepoRootRequest)(nil),          // 0: rig.v1.GetRepoRootRequest
	(*GetRepoRootResponse)(nil),         // 1: rig.v1.GetRepoRootResponse
	(*GetRepoNameRequest)(nil),          // 2: rig.v1.GetRepoNameRequest
	(*GetRepoNameResponse)(nil),         // 3: rig.v1.GetRepoNameResponse
	(*GetDefaultBranchRequest)(nil),     // 4: rig.v1.GetDefaultBranchRequest
	(*GetDefaultBranchResponse)(nil),    // 5: rig.v1.GetDefaultBranchResponse
	(*CreateWorktreeRequest)(nil),       // 6: rig.v1.CreateWorktreeRequest
	(*CreateWorktreeResponse)(nil),      // 7: rig.v1.CreateWorktreeResponse
	(*ListWorktreesRequest)(nil),        // 8: rig.v1.ListWorktreesRequest
	(*WorktreeInfo)(nil),                // 9: rig.v1.WorktreeInfo
	(*ListWorktreesResponse)(nil),       // 10: rig.v1.ListWorktreesResponse
	(*RemoveWorktreeRequest)(nil),       // 11: rig.v1.RemoveWorktreeRequest
	(*RemoveWorktreeResponse)(nil),      // 12: rig.v1.RemoveWorktreeResponse
	(*ForceRemoveWorktreeRequest)(nil),  // 13: rig.v1.ForceRemoveWorktreeRequest
	(*ForceRemoveWorktreeResponse)(nil), // 14: rig.v1.ForceRemoveWorktreeResponse
	(*GetWorktreePathRequest)(nil),      // 15: rig.v1.GetWorktreePathRequest
	(*GetWorktreePathResponse)(nil),     // 16: rig.v1.GetWorktreePathResponse
	(*CloneRequest)(nil),                // 17: rig.v1.CloneRequest
	(*CloneResponse)(nil),               // 18: rig.v1.CloneResponse
	(*IsBranchMergedRequest)(nil),       // 19: rig.v1.IsBranchMergedRequest
	(*IsBranchMergedResponse)(nil),      // 20: rig.v1.IsBranchMergedResponse
}
var file_pkg_api_v1_vcs_proto_depIdxs = []int32{
	9,  // 0: rig.v1.ListWorktreesResponse.worktrees:type_name -> rig.v1.WorktreeInfo
	0,  // 1: rig.v1.VCSService.GetRepoRoot:input_type -> rig.v1.GetRepoRootRequest
	2,  // 2: rig.v1.VCSService.GetRepoName:input_type -> rig.v1.GetRepoNameRequest
	4,  // 3: rig.v1.VCSService.GetDefaultBranch:input_type -> rig.v1.GetDefaultBranchRequest
	6,  // 4: rig.v1.VCSService.CreateWorktree:input_type -> rig.v1.CreateWorktreeRequest
	8,  // 5: rig.v1.VCSService.ListWorktrees:input_type -> rig.v1.ListWorktreesRequest
	11, // 6: rig.v1.VCSService.RemoveWorktree:input_type -> rig.v1.RemoveWorktreeRequest
	13, // 7: rig.v1.VCSService.ForceRemoveWorktree:input_type -> rig.v1.ForceRemoveWorktreeRequest
	15, // 8: rig.v1.VCSService.GetWorktreePath:input_type -> rig.v1.GetWorktreePathRequest
	17, // 9: rig.v1.VCSService.Clone:input_type -> rig.v1.CloneRequest
	19, // 10: rig.v1.VCSService.IsBranchMerged:input_type -> rig.v1.IsBranchMergedRequest
	1,  // 11: rig.v1.VCSService.GetRepoRoot:output_type -> rig.v1.GetRepoRootResponse
	3,  // 12: rig.v1.VCSService.GetRepoName:output_type -> rig.v1.GetRepoNameResponse
	5,  // 13: rig.v1.VCSService.GetDefaultBranch:output_type -> rig.v1.GetDefaultBranchResponse
	7,  // 14: rig.v1.VCSService.CreateWorktree:output_type -> rig.v1.CreateWorktreeResponse
	10, // 15: rig.v1.VCSService.ListWorktrees:output_type -> rig.v1.ListWorktreesResponse
	12, // 16: rig.v1.VCSService.RemoveWorktree:output_type -> rig.v1.RemoveWorktreeResponse
	14, // 17: rig.v1.VCSService.ForceRemoveWorktree:output_type -> rig.v1.ForceRemoveWorktreeResponse
	16, // 18: rig.v1.VCSService.GetWorktreePath:output_type -> rig.v1.GetWorktreePathResponse
	18, // 19: rig.v1.VCSService.Clone:output_type -> rig.v1.CloneResponse
	20, // 20: rig.v1.VCSService.IsBranchMerged:output_type -> rig.v1.IsBranchMergedResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_vcs_proto_init() }
func file_pkg_api_v1_vcs_proto_init() {
	if File_pkg_api_v1_vcs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_vcs_proto_rawDesc), len(file_pkg_api_v1_vcs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_vcs_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_vcs_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_vcs_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_vcs_proto = out.File
	file_pkg_api_v1_vcs_proto_goTypes = nil
	file_pkg_api_v1_vcs_proto_depIdxs = nil
}
