// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/api/v1/vcs.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VCSService_GetRepoRoot_FullMethodName         = "/rig.v1.VCSService/GetRepoRoot"
	VCSService_GetRepoName_FullMethodName         = "/rig.v1.VCSService/GetRepoName"
	VCSService_GetDefaultBranch_FullMethodName    = "/rig.v1.VCSService/GetDefaultBranch"
	VCSService_CreateWorktree_FullMethodName      = "/rig.v1.VCSService/CreateWorktree"
	VCSService_ListWorktrees_FullMethodName       = "/rig.v1.VCSService/ListWorktrees"
	VCSService_RemoveWorktree_FullMethodName      = "/rig.v1.VCSService/RemoveWorktree"
	VCSService_ForceRemoveWorktree_FullMethodName = "/rig.v1.VCSService/ForceRemoveWorktree"
	VCSService_GetWorktreePath_FullMethodName     = "/rig.v1.VCSService/GetWorktreePath"
	VCSService_Clone_FullMethodName               = "/rig.v1.VCSService/Clone"
	VCSService_IsBranchMerged_FullMethodName      = "/rig.v1.VCSService/IsBranchMerged"
)

// VCSServiceClient is the client API for VCSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VCSService defines the interface for Version Control System operations.
type VCSServiceClient interface {
	// GetRepoRoot returns the root directory of the repository containing the path.
	GetRepoRoot(ctx context.Context, in *GetRepoRootRequest, opts ...grpc.CallOption) (*GetRepoRootResponse, error)
	// GetRepoName returns the name of the repository.
	GetRepoName(ctx context.Context, in *GetRepoNameRequest, opts ...grpc.CallOption) (*GetRepoNameResponse, error)
	// GetDefaultBranch determines the default branch of the repository.
	GetDefaultBranch(ctx context.Context, in *GetDefaultBranchRequest, opts ...grpc.CallOption) (*GetDefaultBranchResponse, error)
	// CreateWorktree creates a new worktree for the given ticket.
	CreateWorktree(ctx context.Context, in *CreateWorktreeRequest, opts ...grpc.CallOption) (*CreateWorktreeResponse, error)
	// ListWorktrees returns a detailed list of all existing worktrees in the repository.
	ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error)
	// RemoveWorktree removes a worktree.
	RemoveWorktree(ctx context.Context, in *RemoveWorktreeRequest, opts ...grpc.CallOption) (*RemoveWorktreeResponse, error)
	// ForceRemoveWorktree removes a worktree even if it has uncommitted changes.
	ForceRemoveWorktree(ctx context.Context, in *ForceRemoveWorktreeRequest, opts ...grpc.CallOption) (*ForceRemoveWorktreeResponse, error)
	// GetWorktreePath returns the absolute path for a ticket's worktree.
	GetWorktreePath(ctx context.Context, in *GetWorktreePathRequest, opts ...grpc.CallOption) (*GetWorktreePathResponse, error)
	// Clone clones a repository from the given URL to the base path.
	Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*CloneResponse, error)
	// IsBranchMerged checks if the given branch is merged into the base branch.
	IsBranchMerged(ctx context.Context, in *IsBranchMergedRequest, opts ...grpc.CallOption) (*IsBranchMergedResponse, error)
}

type vCSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVCSServiceClient(cc grpc.ClientConnInterface) VCSServiceClient {
	return &vCSServiceClient{cc}
}

func (c *vCSServiceClient) GetRepoRoot(ctx context.Context, in *GetRepoRootRequest, opts ...grpc.CallOption) (*GetRepoRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepoRootResponse)
	err := c.cc.Invoke(ctx, VCSService_GetRepoRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) GetRepoName(ctx context.Context, in *GetRepoNameRequest, opts ...grpc.CallOption) (*GetRepoNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepoNameResponse)
	err := c.cc.Invoke(ctx, VCSService_GetRepoName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) GetDefaultBranch(ctx context.Context, in *GetDefaultBranchRequest, opts ...grpc.CallOption) (*GetDefaultBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefaultBranchResponse)
	err := c.cc.Invoke(ctx, VCSService_GetDefaultBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) CreateWorktree(ctx context.Context, in *CreateWorktreeRequest, opts ...grpc.CallOption) (*CreateWorktreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorktreeResponse)
	err := c.cc.Invoke(ctx, VCSService_CreateWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorktreesResponse)
	err := c.cc.Invoke(ctx, VCSService_ListWorktrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) RemoveWorktree(ctx context.Context, in *RemoveWorktreeRequest, opts ...grpc.CallOption) (*RemoveWorktreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWorktreeResponse)
	err := c.cc.Invoke(ctx, VCSService_RemoveWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) ForceRemoveWorktree(ctx context.Context, in *ForceRemoveWorktreeRequest, opts ...grpc.CallOption) (*ForceRemoveWorktreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceRemoveWorktreeResponse)
	err := c.cc.Invoke(ctx, VCSService_ForceRemoveWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) GetWorktreePath(ctx context.Context, in *GetWorktreePathRequest, opts ...grpc.CallOption) (*GetWorktreePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorktreePathResponse)
	err := c.cc.Invoke(ctx, VCSService_GetWorktreePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*CloneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneResponse)
	err := c.cc.Invoke(ctx, VCSService_Clone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSServiceClient) IsBranchMerged(ctx context.Context, in *IsBranchMergedRequest, opts ...grpc.CallOption) (*IsBranchMergedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsBranchMergedResponse)
	err := c.cc.Invoke(ctx, VCSService_IsBranchMerged_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VCSServiceServer is the server API for VCSService service.
// All implementations must embed UnimplementedVCSServiceServer
// for forward compatibility.
//
// VCSService defines the interface for Version Control System operations.
type VCSServiceServer interface {
	// GetRepoRoot returns the root directory of the repository containing the path.
	GetRepoRoot(context.Context, *GetRepoRootRequest) (*GetRepoRootResponse, error)
	// GetRepoName returns the name of the repository.
	GetRepoName(context.Context, *GetRepoNameRequest) (*GetRepoNameResponse, error)
	// GetDefaultBranch determines the default branch of the repository.
	GetDefaultBranch(context.Context, *GetDefaultBranchRequest) (*GetDefaultBranchResponse, error)
	// CreateWorktree creates a new worktree for the given ticket.
	CreateWorktree(context.Context, *CreateWorktreeRequest) (*CreateWorktreeResponse, error)
	// ListWorktrees returns a detailed list of all existing worktrees in the repository.
	ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error)
	// RemoveWorktree removes a worktree.
	RemoveWorktree(context.Context, *RemoveWorktreeRequest) (*RemoveWorktreeResponse, error)
	// ForceRemoveWorktree removes a worktree even if it has uncommitted changes.
	ForceRemoveWorktree(context.Context, *ForceRemoveWorktreeRequest) (*ForceRemoveWorktreeResponse, error)
	// GetWorktreePath returns the absolute path for a ticket's worktree.
	GetWorktreePath(context.Context, *GetWorktreePathRequest) (*GetWorktreePathResponse, error)
	// Clone clones a repository from the given URL to the base path.
	Clone(context.Context, *CloneRequest) (*CloneResponse, error)
	// IsBranchMerged checks if the given branch is merged into the base branch.
	IsBranchMerged(context.Context, *IsBranchMergedRequest) (*IsBranchMergedResponse, error)
	mustEmbedUnimplementedVCSServiceServer()
}

// UnimplementedVCSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVCSServiceServer struct{}

func (UnimplementedVCSServiceServer) GetRepoRoot(context.Context, *GetRepoRootRequest) (*GetRepoRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepoRoot not implemented")
}
func (UnimplementedVCSServiceServer) GetRepoName(context.Context, *GetRepoNameRequest) (*GetRepoNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepoName not implemented")
}
func (UnimplementedVCSServiceServer) GetDefaultBranch(context.Context, *GetDefaultBranchRequest) (*GetDefaultBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultBranch not implemented")
}
func (UnimplementedVCSServiceServer) CreateWorktree(context.Context, *CreateWorktreeRequest) (*CreateWorktreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorktree not implemented")
}
func (UnimplementedVCSServiceServer) ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorktrees not implemented")
}
func (UnimplementedVCSServiceServer) RemoveWorktree(context.Context, *RemoveWorktreeRequest) (*RemoveWorktreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWorktree not implemented")
}
func (UnimplementedVCSServiceServer) ForceRemoveWorktree(context.Context, *ForceRemoveWorktreeRequest) (*ForceRemoveWorktreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceRemoveWorktree not implemented")
}
func (UnimplementedVCSServiceServer) GetWorktreePath(context.Context, *GetWorktreePathRequest) (*GetWorktreePathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorktreePath not implemented")
}
func (UnimplementedVCSServiceServer) Clone(context.Context, *CloneRequest) (*CloneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedVCSServiceServer) IsBranchMerged(context.Context, *IsBranchMergedRequest) (*IsBranchMergedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsBranchMerged not implemented")
}
func (UnimplementedVCSServiceServer) mustEmbedUnimplementedVCSServiceServer() {}
func (UnimplementedVCSServiceServer) testEmbeddedByValue()                    {}

// UnsafeVCSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VCSServiceServer will
// result in compilation errors.
type UnsafeVCSServiceServer interface {
	mustEmbedUnimplementedVCSServiceServer()
}

func RegisterVCSServiceServer(s grpc.ServiceRegistrar, srv VCSServiceServer) {
	// If the following call pancis, it indicates UnimplementedVCSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VCSService_ServiceDesc, srv)
}

func _VCSService_GetRepoRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).GetRepoRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_GetRepoRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).GetRepoRoot(ctx, req.(*GetRepoRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_GetRepoName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).GetRepoName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_GetRepoName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).GetRepoName(ctx, req.(*GetRepoNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_GetDefaultBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).GetDefaultBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_GetDefaultBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).GetDefaultBranch(ctx, req.(*GetDefaultBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_CreateWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).CreateWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_CreateWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).CreateWorktree(ctx, req.(*CreateWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_ListWorktrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorktreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).ListWorktrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_ListWorktrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).ListWorktrees(ctx, req.(*ListWorktreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_RemoveWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).RemoveWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_RemoveWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).RemoveWorktree(ctx, req.(*RemoveWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_ForceRemoveWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceRemoveWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).ForceRemoveWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_ForceRemoveWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).ForceRemoveWorktree(ctx, req.(*ForceRemoveWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_GetWorktreePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorktreePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).GetWorktreePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_GetWorktreePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).GetWorktreePath(ctx, req.(*GetWorktreePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).Clone(ctx, req.(*CloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSService_IsBranchMerged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBranchMergedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServiceServer).IsBranchMerged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCSService_IsBranchMerged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServiceServer).IsBranchMerged(ctx, req.(*IsBranchMergedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VCSService_ServiceDesc is the grpc.ServiceDesc for VCSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VCSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rig.v1.VCSService",
	HandlerType: (*VCSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRepoRoot",
			Handler:    _VCSService_GetRepoRoot_Handler,
		},
		{
			MethodName: "GetRepoName",
			Handler:    _VCSService_GetRepoName_Handler,
		},
		{
			MethodName: "GetDefaultBranch",
			Handler:    _VCSService_GetDefaultBranch_Handler,
		},
		{
			MethodName: "CreateWorktree",
			Handler:    _VCSService_CreateWorktree_Handler,
		},
		{
			MethodName: "ListWorktrees",
			Handler:    _VCSService_ListWorktrees_Handler,
		},
		{
			MethodName: "RemoveWorktree",
			Handler:    _VCSService_RemoveWorktree_Handler,
		},
		{
			MethodName: "ForceRemoveWorktree",
			Handler:    _VCSService_ForceRemoveWorktree_Handler,
		},
		{
			MethodName: "GetWorktreePath",
			Handler:    _VCSService_GetWorktreePath_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _VCSService_Clone_Handler,
		},
		{
			MethodName: "IsBranchMerged",
			Handler:    _VCSService_IsBranchMerged_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/v1/vcs.proto",
}
