// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"thoreinstein.com/rig/pkg/api/v1"
)

// NewMockKnowledgeServiceClient creates a new instance of MockKnowledgeServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKnowledgeServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKnowledgeServiceClient {
	mock := &MockKnowledgeServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKnowledgeServiceClient is an autogenerated mock type for the KnowledgeServiceClient type
type MockKnowledgeServiceClient struct {
	mock.Mock
}

type MockKnowledgeServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKnowledgeServiceClient) EXPECT() *MockKnowledgeServiceClient_Expecter {
	return &MockKnowledgeServiceClient_Expecter{mock: &_m.Mock}
}

// CreateTicketNote provides a mock function for the type MockKnowledgeServiceClient
func (_mock *MockKnowledgeServiceClient) CreateTicketNote(ctx context.Context, in *apiv1.CreateTicketNoteRequest, opts ...grpc.CallOption) (*apiv1.CreateTicketNoteResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateTicketNote")
	}

	var r0 *apiv1.CreateTicketNoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.CreateTicketNoteRequest, ...grpc.CallOption) (*apiv1.CreateTicketNoteResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.CreateTicketNoteRequest, ...grpc.CallOption) *apiv1.CreateTicketNoteResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.CreateTicketNoteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.CreateTicketNoteRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeServiceClient_CreateTicketNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicketNote'
type MockKnowledgeServiceClient_CreateTicketNote_Call struct {
	*mock.Call
}

// CreateTicketNote is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apiv1.CreateTicketNoteRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) CreateTicketNote(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_CreateTicketNote_Call {
	return &MockKnowledgeServiceClient_CreateTicketNote_Call{Call: _e.mock.On("CreateTicketNote",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_CreateTicketNote_Call) Run(run func(ctx context.Context, in *apiv1.CreateTicketNoteRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_CreateTicketNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.CreateTicketNoteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.CreateTicketNoteRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_CreateTicketNote_Call) Return(createTicketNoteResponse *apiv1.CreateTicketNoteResponse, err error) *MockKnowledgeServiceClient_CreateTicketNote_Call {
	_c.Call.Return(createTicketNoteResponse, err)
	return _c
}

func (_c *MockKnowledgeServiceClient_CreateTicketNote_Call) RunAndReturn(run func(ctx context.Context, in *apiv1.CreateTicketNoteRequest, opts ...grpc.CallOption) (*apiv1.CreateTicketNoteResponse, error)) *MockKnowledgeServiceClient_CreateTicketNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetDailyNotePath provides a mock function for the type MockKnowledgeServiceClient
func (_mock *MockKnowledgeServiceClient) GetDailyNotePath(ctx context.Context, in *apiv1.GetDailyNotePathRequest, opts ...grpc.CallOption) (*apiv1.GetDailyNotePathResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetDailyNotePath")
	}

	var r0 *apiv1.GetDailyNotePathResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.GetDailyNotePathRequest, ...grpc.CallOption) (*apiv1.GetDailyNotePathResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.GetDailyNotePathRequest, ...grpc.CallOption) *apiv1.GetDailyNotePathResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.GetDailyNotePathResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.GetDailyNotePathRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeServiceClient_GetDailyNotePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyNotePath'
type MockKnowledgeServiceClient_GetDailyNotePath_Call struct {
	*mock.Call
}

// GetDailyNotePath is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apiv1.GetDailyNotePathRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) GetDailyNotePath(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_GetDailyNotePath_Call {
	return &MockKnowledgeServiceClient_GetDailyNotePath_Call{Call: _e.mock.On("GetDailyNotePath",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_GetDailyNotePath_Call) Run(run func(ctx context.Context, in *apiv1.GetDailyNotePathRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_GetDailyNotePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.GetDailyNotePathRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.GetDailyNotePathRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_GetDailyNotePath_Call) Return(getDailyNotePathResponse *apiv1.GetDailyNotePathResponse, err error) *MockKnowledgeServiceClient_GetDailyNotePath_Call {
	_c.Call.Return(getDailyNotePathResponse, err)
	return _c
}

func (_c *MockKnowledgeServiceClient_GetDailyNotePath_Call) RunAndReturn(run func(ctx context.Context, in *apiv1.GetDailyNotePathRequest, opts ...grpc.CallOption) (*apiv1.GetDailyNotePathResponse, error)) *MockKnowledgeServiceClient_GetDailyNotePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotePath provides a mock function for the type MockKnowledgeServiceClient
func (_mock *MockKnowledgeServiceClient) GetNotePath(ctx context.Context, in *apiv1.GetNotePathRequest, opts ...grpc.CallOption) (*apiv1.GetNotePathResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNotePath")
	}

	var r0 *apiv1.GetNotePathResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.GetNotePathRequest, ...grpc.CallOption) (*apiv1.GetNotePathResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.GetNotePathRequest, ...grpc.CallOption) *apiv1.GetNotePathResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.GetNotePathResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.GetNotePathRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeServiceClient_GetNotePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotePath'
type MockKnowledgeServiceClient_GetNotePath_Call struct {
	*mock.Call
}

// GetNotePath is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apiv1.GetNotePathRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) GetNotePath(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_GetNotePath_Call {
	return &MockKnowledgeServiceClient_GetNotePath_Call{Call: _e.mock.On("GetNotePath",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_GetNotePath_Call) Run(run func(ctx context.Context, in *apiv1.GetNotePathRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_GetNotePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.GetNotePathRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.GetNotePathRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_GetNotePath_Call) Return(getNotePathResponse *apiv1.GetNotePathResponse, err error) *MockKnowledgeServiceClient_GetNotePath_Call {
	_c.Call.Return(getNotePathResponse, err)
	return _c
}

func (_c *MockKnowledgeServiceClient_GetNotePath_Call) RunAndReturn(run func(ctx context.Context, in *apiv1.GetNotePathRequest, opts ...grpc.CallOption) (*apiv1.GetNotePathResponse, error)) *MockKnowledgeServiceClient_GetNotePath_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDailyNote provides a mock function for the type MockKnowledgeServiceClient
func (_mock *MockKnowledgeServiceClient) UpdateDailyNote(ctx context.Context, in *apiv1.UpdateDailyNoteRequest, opts ...grpc.CallOption) (*apiv1.UpdateDailyNoteResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateDailyNote")
	}

	var r0 *apiv1.UpdateDailyNoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.UpdateDailyNoteRequest, ...grpc.CallOption) (*apiv1.UpdateDailyNoteResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.UpdateDailyNoteRequest, ...grpc.CallOption) *apiv1.UpdateDailyNoteResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.UpdateDailyNoteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.UpdateDailyNoteRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeServiceClient_UpdateDailyNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDailyNote'
type MockKnowledgeServiceClient_UpdateDailyNote_Call struct {
	*mock.Call
}

// UpdateDailyNote is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apiv1.UpdateDailyNoteRequest
//   - opts ...grpc.CallOption
func (_e *MockKnowledgeServiceClient_Expecter) UpdateDailyNote(ctx interface{}, in interface{}, opts ...interface{}) *MockKnowledgeServiceClient_UpdateDailyNote_Call {
	return &MockKnowledgeServiceClient_UpdateDailyNote_Call{Call: _e.mock.On("UpdateDailyNote",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockKnowledgeServiceClient_UpdateDailyNote_Call) Run(run func(ctx context.Context, in *apiv1.UpdateDailyNoteRequest, opts ...grpc.CallOption)) *MockKnowledgeServiceClient_UpdateDailyNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.UpdateDailyNoteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.UpdateDailyNoteRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKnowledgeServiceClient_UpdateDailyNote_Call) Return(updateDailyNoteResponse *apiv1.UpdateDailyNoteResponse, err error) *MockKnowledgeServiceClient_UpdateDailyNote_Call {
	_c.Call.Return(updateDailyNoteResponse, err)
	return _c
}

func (_c *MockKnowledgeServiceClient_UpdateDailyNote_Call) RunAndReturn(run func(ctx context.Context, in *apiv1.UpdateDailyNoteRequest, opts ...grpc.CallOption) (*apiv1.UpdateDailyNoteResponse, error)) *MockKnowledgeServiceClient_UpdateDailyNote_Call {
	_c.Call.Return(run)
	return _c
}
