// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"thoreinstein.com/rig/pkg/api/v1"
)

// NewMockPluginManager creates a new instance of MockPluginManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPluginManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPluginManager {
	mock := &MockPluginManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPluginManager is an autogenerated mock type for the PluginManager type
type MockPluginManager struct {
	mock.Mock
}

type MockPluginManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPluginManager) EXPECT() *MockPluginManager_Expecter {
	return &MockPluginManager_Expecter{mock: &_m.Mock}
}

// GetKnowledgeClient provides a mock function for the type MockPluginManager
func (_mock *MockPluginManager) GetKnowledgeClient(ctx context.Context, name string) (apiv1.KnowledgeServiceClient, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetKnowledgeClient")
	}

	var r0 apiv1.KnowledgeServiceClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (apiv1.KnowledgeServiceClient, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) apiv1.KnowledgeServiceClient); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiv1.KnowledgeServiceClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginManager_GetKnowledgeClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKnowledgeClient'
type MockPluginManager_GetKnowledgeClient_Call struct {
	*mock.Call
}

// GetKnowledgeClient is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPluginManager_Expecter) GetKnowledgeClient(ctx interface{}, name interface{}) *MockPluginManager_GetKnowledgeClient_Call {
	return &MockPluginManager_GetKnowledgeClient_Call{Call: _e.mock.On("GetKnowledgeClient", ctx, name)}
}

func (_c *MockPluginManager_GetKnowledgeClient_Call) Run(run func(ctx context.Context, name string)) *MockPluginManager_GetKnowledgeClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPluginManager_GetKnowledgeClient_Call) Return(knowledgeServiceClient apiv1.KnowledgeServiceClient, err error) *MockPluginManager_GetKnowledgeClient_Call {
	_c.Call.Return(knowledgeServiceClient, err)
	return _c
}

func (_c *MockPluginManager_GetKnowledgeClient_Call) RunAndReturn(run func(ctx context.Context, name string) (apiv1.KnowledgeServiceClient, error)) *MockPluginManager_GetKnowledgeClient_Call {
	_c.Call.Return(run)
	return _c
}

// ReleasePlugin provides a mock function for the type MockPluginManager
func (_mock *MockPluginManager) ReleasePlugin(name string) {
	_mock.Called(name)
	return
}

// MockPluginManager_ReleasePlugin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleasePlugin'
type MockPluginManager_ReleasePlugin_Call struct {
	*mock.Call
}

// ReleasePlugin is a helper method to define mock.On call
//   - name string
func (_e *MockPluginManager_Expecter) ReleasePlugin(name interface{}) *MockPluginManager_ReleasePlugin_Call {
	return &MockPluginManager_ReleasePlugin_Call{Call: _e.mock.On("ReleasePlugin", name)}
}

func (_c *MockPluginManager_ReleasePlugin_Call) Run(run func(name string)) *MockPluginManager_ReleasePlugin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginManager_ReleasePlugin_Call) Return() *MockPluginManager_ReleasePlugin_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPluginManager_ReleasePlugin_Call) RunAndReturn(run func(name string)) *MockPluginManager_ReleasePlugin_Call {
	_c.Run(run)
	return _c
}
